package vr.implantacao.dao.atualizador;

import java.sql.Statement;
import vrframework.classe.Conexao;

/**
 *
 * @author Desenvolvimento
 */

public class AtualizadorDAO {

    public void criarSchema() throws Exception {
        try (Statement stm = Conexao.createStatement()) {
            stm.execute("CREATE SCHEMA IF NOT EXISTS implantacao2_5");
        }
    }

    public void criarTabelas() throws Exception {
        try (Statement stm = Conexao.createStatement()) {
            stm.execute(
                    "CREATE TABLE implantacao2_5.bancodados(\n"
                    + "	id serial PRIMARY KEY NOT NULL,\n"
                    + "	nome VARCHAR(60) NOT NULL\n"
                    + ");"
                    + "\n"
                    + "CREATE TABLE IF NOT EXISTS implantacao2_5.sistema(\n"
                    + "	id serial PRIMARY KEY NOT NULL,\n"
                    + "	nome VARCHAR(60) NOT NULL\n"
                    + ");\n"
                    + "\n"
                    + "CREATE TABLE IF NOT EXISTS implantacao2_5.sistemabancodados(\n"
                    + "	id serial PRIMARY KEY NOT NULL,\n"
                    + "	id_sistema INTEGER NOT NULL,\n"
                    + "	id_bancodados INTEGER NOT NULL,\n"
                    + "	nomeschema VARCHAR(60),\n"
                    + "	usuario VARCHAR(30),\n"
                    + "	senha VARCHAR(30),\n"
                    + "	CONSTRAINT fk_id_sistema FOREIGN KEY (id_sistema)\n"
                    + "		REFERENCES implantacao2_5.sistema (id),\n"
                    + "	CONSTRAINT fk_id_bancodados FOREIGN KEY (id_bancodados)\n"
                    + "		REFERENCES implantacao2_5.bancodados (id),\n"
                    + "	CONSTRAINT un_sistema_bancodados \n"
                    + "		UNIQUE (id_sistema, id_bancodados)\n"
                    + ");"
                    + "\n"
                    + "CREATE TABLE IF NOT EXISTS implantacao2_5.conexao(\n"
                    + "	id serial PRIMARY KEY NOT NULL,\n"
                    + "	host VARCHAR(20) NOT NULL,\n"
                    + "	porta INTEGER NOT NULL,\n"
                    + "	usuario VARCHAR(30) NOT NULL,\n"
                    + "	senha VARCHAR(30) NOT NULL,\n"
                    + "	descricao VARCHAR (60),\n"
                    + "	id_sistemabancodados INTEGER NOT NULL,\n"
                    + "	CONSTRAINT fk_id_sistemabancodados FOREIGN KEY (id_sistemabancodados)\n"
                    + "		REFERENCES implantacao2_5.sistemabancodados (id)\n"
                    + ");"
                    + "\n"
                    + "CREATE TABLE IF NOT EXISTS implantacao2_5.conexaoloja(\n"
                    + "	id serial PRIMARY KEY NOT NULL,\n"
                    + "	id_conexao INTEGER NOT NULL,\n"
                    + "	id_lojaorigem VARCHAR NOT NULL,\n"
                    + "	id_lojadestino INTEGER NOT NULL,\n"
                    + "	datacadastro TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),\n"
                    + "	id_situacaomigracao INTEGER NOT NULL,\n"
                    + "	lojamatriz BOOLEAN,\n"
                    + "	CONSTRAINT fk_if_conexao FOREIGN KEY (id_conexao)\n"
                    + "		REFERENCES implantacao2_5.conexao(id)\n"
                    + ");"
            );
        }
    }

    public void inserirTabelaBancoDados() throws Exception {
        try (Statement stm = Conexao.createStatement()) {
            stm.execute(
                    "INSERT INTO implantacao2_5.bancodados (nome) VALUES (upper('Access'));\n"
                    + "INSERT INTO implantacao2_5.bancodados (nome) VALUES (upper('ADS'));\n"
                    + "INSERT INTO implantacao2_5.bancodados (nome) VALUES (upper('Cache'));\n"
                    + "INSERT INTO implantacao2_5.bancodados (nome) VALUES (upper('Dbf'));\n"
                    + "INSERT INTO implantacao2_5.bancodados (nome) VALUES (upper('Firebird'));\n"
                    + "INSERT INTO implantacao2_5.bancodados (nome) VALUES (upper('DB2'));\n"
                    + "INSERT INTO implantacao2_5.bancodados (nome) VALUES (upper('Informix'));\n"
                    + "INSERT INTO implantacao2_5.bancodados (nome) VALUES (upper('MySQL'));\n"
                    + "INSERT INTO implantacao2_5.bancodados (nome) VALUES (upper('Oracle'));\n"
                    + "INSERT INTO implantacao2_5.bancodados (nome) VALUES (upper('Paradox'));\n"
                    + "INSERT INTO implantacao2_5.bancodados (nome) VALUES (upper('PostgresSQL'));\n"
                    + "INSERT INTO implantacao2_5.bancodados (nome) VALUES (upper('SQLite'));\n"
                    + "INSERT INTO implantacao2_5.bancodados (nome) VALUES (upper('SQL Server'));"
            );
        }
    }

    public void inserirTabelaSistema() throws Exception {
        try (Statement stm = Conexao.createStatement()) {
            stm.execute(
                    "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('ASoft'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Accesys'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Acom'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('AlphaSys'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Apollo'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('ArtSystem'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Asefe'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Atenas'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Athos'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Atma'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('AutoAdm'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('AutoSystem'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Autocom'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Automaq'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Avance'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Avistare'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Base'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('BrainSoft'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('BrajanGestores'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('CFSoftSiaECF'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('CPGestor'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('CPlus'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('CadastraFacil'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Cefas'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Cerebro'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Cervantes'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Cga'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Ciss'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Click'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Contech'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('ControlWare'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('ControlX'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Cronos20'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Cupermax'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('DJSystem'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('DLink'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('DSoft'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('DataSync'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Delfi'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Destro'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('DevMaster'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Director'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('DtCom'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('EasySac'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Emporio'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Eptus'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('EsSystem'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Etica'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Exodus'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('FHOnline'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('FabTech'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Facilite'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Farm2000'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Fenix'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Flash'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Flatan'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('FortDAO'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Futura'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('G10'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('G3'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('GCom'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('GDI'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('GDoor'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('GR7'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('GTech'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('GZSistemas'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('GestorPdv'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('GetWay'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Gigatron'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Gondola'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('GuiaSistemas'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('HRTech'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('HerculesIntCash'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Hipcom'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Hiper'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('ICommerce'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('IQSistemas'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('IServer'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('InfoBrasil'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('InfoMac'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Inova'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('IntelliCash'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Intellicon'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('InterData'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Interage'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Inventer'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('JM2Online'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('JMaster'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Jacsys'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Jrf'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Kairos'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Kcms'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('LBSoftware'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('LiderNetWork'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Lince'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Linear'));"                            
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Linner'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Liteci'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('LogTEC'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Logicbox'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Logus'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Lyncis'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('MSIInfor'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Market'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Master'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('MercaLite'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Milenio'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Mobility'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('MobnePdv'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Mrs'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('MultiPdv'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('NATISistemas'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('NCA'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Open'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Orion'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('OrionTech'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Oryon'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Phixa'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('PlenoKW'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Plenus'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Poligon'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Pomares'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Prosuper'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Proton'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('PwGestor'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Pws'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('RCNet'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('RKSoftware'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('RMSAutomaHelp'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('RMS'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('RPInfo'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Rensoftware'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Repleis'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('ResultMais'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Rootac'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('SDInformatica'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('SGMaster'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('SIMS'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('STI'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('STSitemas'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Saac'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('SabTech'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Saef'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('SambaNet'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Satecfe'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Sav'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Scef'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Shi'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('SiaCriare'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Siac'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Sifat'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Sigma'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Siit'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Sircom'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('SisMoura'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('SnSistema'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Softcom'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Softtech'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Solido'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Solidus'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('SolutionSupera'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Sophyx'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Sri'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('SuperServer'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Super'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('SuperLoja10'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Superus'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('SyncTec'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('SysAut'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('SysERP'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('SysPdv'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Sysmo'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('TGA'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Tecnosoft'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Telecon'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('TiTecnologia'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('TopSystem'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('TpaRootac'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Tsti'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Uniplus'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('UpForti'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('VCash'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('VRMaster'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('ViaSoft'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Viggo'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('VisualComercio'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('VisualMix'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('W2A'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('WebSaq'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Weber'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('WinNexus'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('WisaSoft'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Wmsi'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('WShop'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Zoombox'));\n"
                    + "INSERT INTO implantacao2_5.sistema (nome) VALUES (upper('Zpf'));\n"                    
            );
        }
    }

    public void inserirTabelaSistemaBancoDados() throws Exception {
        try (Statement stm = Conexao.createStatement()) {
            stm.execute(
                    "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome LIKE '%SYSPDV%'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome LIKE '%FIREBIRD%'), 'SYSDBA', 'masterkey', null);\n"
                    + "\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome LIKE '%RKSOFTWARE%'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome LIKE '%FIREBIRD%'), 'SYSDBA', 'Office25', null);\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome LIKE '%LINEAR%'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome LIKE '%MYSQL%'), 'adminlinear', '@2013linear', 'sglinx');\n"
                    + "\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome LIKE '%ISERVER%'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome LIKE '%MYSQL%'), 'root', '750051', 'db_iserver');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome LIKE '%TSTI%'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome LIKE '%MYSQL%'), 'tsti', '1234', 'tsl');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome LIKE '%SIRCOM%'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome LIKE '%FIREBIRD%'), 'SYSDBA', 'masterkey', null);\n"
                    + "\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome LIKE '%INTELICASH%'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome LIKE '%FIREBIRD%'), 'SYSDBA', 'masterkey', null);\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome LIKE '%FUTURA%'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome LIKE '%FIREBIRD%'), 'SYSDBA', 'sbofutura', 'Dados.fdb');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome LIKE '%LOGUS%'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome LIKE '%INFORMIX%'), 'informix', 'loooge', null);\n"
                    + "\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome LIKE '%SIIT%'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome LIKE '%MYSQL%'), 'root', 'JesusCristo', null);\n"
                    + "\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome LIKE '%AVANCE%'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome LIKE '%MYSQL%'), 'root', 'infor', null);\n"
                    + "\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome LIKE '%GZSISTEMAS%'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome LIKE '%MYSQL%'), 'root', 'mestre', null);\n"
                    + "\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome LIKE '%SIACRIARE%'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome LIKE '%MYSQL%'), 'root', 'Hs8Tw13kPx7uDPs', null);\n"
                    + "\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome LIKE '%HIPCOM%'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome LIKE '%MYSQL%'), 'root', 'hpc00', null);\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome LIKE '%ARIUS%'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome LIKE '%ORACLE%'), 'PROREG', 'automa', null);\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome LIKE '%SUPERUS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome LIKE '%ORACLE%'), 'xe', 'smart', null);\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome LIKE '%DEVMASTER'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome LIKE '%POSTGRESQL%'), 'devmaster', 'devmaster', null); \n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome LIKE '%BRAJAN%'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome LIKE '%POSTGRESQL%'), 'postgres', 'orple', null); \n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome LIKE '%NCA%'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome LIKE '%POSTGRESQL%'), 'postgres', 'post', null);  \n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome LIKE '%UNIPLUS%'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome LIKE '%POSTGRESQL%'), 'postgres', 'postgres', null);   \n"
                    + "\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome LIKE '%ATHOS%'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome LIKE '%POSTGRESQL%'), 'athos', 'j2mhw82dyu1kn5g4', null);   	 \n"
                    + "\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome LIKE '%RESULTMAIS%'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome LIKE '%POSTGRESQL%'), 'postgres', 'rmpostgres', 'rmbancodados');   	  \n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome LIKE '%DIRECTOR%'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome LIKE '%SQL SERVER%'), 'sa', '#1qwer0987', null);   	   \n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome LIKE '%ATENAS%'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome LIKE '%SQL SERVER%'), 'sa', 'personal', 'nca_adm'); \n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome LIKE '%TELECON%'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome LIKE '%SQL SERVER%'), 'sa', 'a2m8x7h5', 'GESTAO');   	     \n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome LIKE '%POLIGON%'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome LIKE '%SQL SERVER%'), 'sa', 'Pol!gon5oft', 'PADARIA');   	     "
            );
        }
    }

    public void criarEstrutura() throws Exception {
        criarSchema();
        criarTabelas();
        inserirTabelaBancoDados();
        inserirTabelaSistema();
        inserirTabelaSistemaBancoDados();
    }
}
