/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vrimplantacao2_5.gui.cadastro.configuracao;

import javax.swing.JOptionPane;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.openide.util.Exceptions;
import vrimplantacao2_5.dao.cadastro.sistemabancodados.SistemaBancoDadosDAO;
import vrimplantacao2_5.vo.cadastro.ScriptLojaOrigemVO;

/**
 *
 * @author Desenvolvimento
 */
public class SalvarScriptLojaOrigemPanel extends javax.swing.JPanel {

    private SistemaBancoDadosDAO dao = new SistemaBancoDadosDAO();
    private String validaDados = null;

    /**
     * Creates new form SalvarScriptLojaOrigemPanel
     */
    public SalvarScriptLojaOrigemPanel() throws Exception {
        initComponents();
        for (ScriptLojaOrigemVO item : dao.getScriptsLojaOrigem()) {
            cboSistema.addItem(item.getSistema());
        }
        for (ScriptLojaOrigemVO item2 : dao.getBancoDados()) {
            cbBancoGenerico.addItem(item2.getBanco());
        }
        nomeBanco.setText("");
        idBanco.setText("");
        txAreaScript.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_SQL);
        txAreaScript.setCodeFoldingEnabled(true);
        validaDados = dao.verificaDadosSistemaGenerico();
        if (validaDados == null) {
            dao.InsereDadosSistemaGenerico();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboSistema = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomeBanco = new javax.swing.JLabel();
        idBanco = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txAreaScript = new org.fife.ui.rsyntaxtextarea.RSyntaxTextArea();
        jLabel5 = new javax.swing.JLabel();
        cbBancoGenerico = new javax.swing.JComboBox<>();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(SalvarScriptLojaOrigemPanel.class, "SalvarScriptLojaOrigemPanel.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(SalvarScriptLojaOrigemPanel.class, "SalvarScriptLojaOrigemPanel.jLabel2.text")); // NOI18N

        cboSistema.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SISTEMAS" }));
        cboSistema.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboSistemaItemStateChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(SalvarScriptLojaOrigemPanel.class, "SalvarScriptLojaOrigemPanel.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(SalvarScriptLojaOrigemPanel.class, "SalvarScriptLojaOrigemPanel.jLabel4.text")); // NOI18N

        nomeBanco.setForeground(new java.awt.Color(0, 0, 153));
        org.openide.awt.Mnemonics.setLocalizedText(nomeBanco, org.openide.util.NbBundle.getMessage(SalvarScriptLojaOrigemPanel.class, "SalvarScriptLojaOrigemPanel.nomeBanco.text")); // NOI18N

        idBanco.setForeground(new java.awt.Color(0, 0, 153));
        org.openide.awt.Mnemonics.setLocalizedText(idBanco, org.openide.util.NbBundle.getMessage(SalvarScriptLojaOrigemPanel.class, "SalvarScriptLojaOrigemPanel.idBanco.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(SalvarScriptLojaOrigemPanel.class, "SalvarScriptLojaOrigemPanel.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txAreaScript.setColumns(20);
        txAreaScript.setRows(5);
        jScrollPane2.setViewportView(txAreaScript);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(SalvarScriptLojaOrigemPanel.class, "SalvarScriptLojaOrigemPanel.jLabel5.text")); // NOI18N

        cbBancoGenerico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BANCOS" }));
        cbBancoGenerico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbBancoGenericoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(cboSistema, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idBanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nomeBanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbBancoGenerico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomeBanco)
                        .addComponent(idBanco)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbBancoGenerico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboSistemaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboSistemaItemStateChanged
        String sistemaSelecionado = cboSistema.getSelectedItem().toString();
        try {
            for (ScriptLojaOrigemVO vo : dao.getScriptsLojaOrigem()) {
                if (sistemaSelecionado.equals(vo.getSistema())) {
                    idBanco.setText(String.valueOf(vo.getIdBanco()));
                    nomeBanco.setText(vo.getBanco());
                    txAreaScript.setText(vo.getScript());
                }
            }
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }

    }//GEN-LAST:event_cboSistemaItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String script = validaScript(txAreaScript.getText());
        dao.atualizarScriptLojaOrigemGenerico(script, idBanco.getText(), nomeBanco.getText());
        dao.atualizaDadosSistemaGenerico(idBanco.getText(), nomeBanco.getText(), script);
        JOptionPane.showMessageDialog(this, "Dados alterados com sucesso!");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbBancoGenericoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbBancoGenericoItemStateChanged
        String bancoSelecionado = cbBancoGenerico.getSelectedItem().toString();
        String script = validaScript(txAreaScript.getText());
        try {
            validaDados = dao.verificaDadosSistemaGenerico();
            for (ScriptLojaOrigemVO vo : dao.getBancoDados()) {
                if (bancoSelecionado.equals(vo.getBanco())) {
                    idBanco.setText(String.valueOf(vo.getIdBanco()));
                    nomeBanco.setText(vo.getBanco());
                    if (validaDados != null) {
                    dao.atualizaDadosSistemaGenerico(idBanco.getText(), nomeBanco.getText(), script);
                    }
                }
            }
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_cbBancoGenericoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbBancoGenerico;
    private javax.swing.JComboBox<String> cboSistema;
    private javax.swing.JLabel idBanco;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nomeBanco;
    private org.fife.ui.rsyntaxtextarea.RSyntaxTextArea txAreaScript;
    // End of variables declaration//GEN-END:variables

    private String validaScript(String script) {
        if (script == null) {
            JOptionPane.showMessageDialog(null, "Favor inserir um script valido contendo alias de id edescrição");
        }
        script = script.toUpperCase().contains("UPDATE") ? "VAZIO"
                : script.toUpperCase().contains("CREATE") ? "VAZIO"
                : script.toUpperCase().contains("INSERT") ? "VAZIO"
                : script.toUpperCase().contains("DELETE") ? "VAZIO"
                : script;
        if (script.equals("VAZIO")) {
            JOptionPane.showMessageDialog(null, "Fovor inserir um script válido!");
        }
        return script;
    }
}
