/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vrimplantacao2_5.conversor;

import java.awt.Color;
import java.awt.Dimension;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.openide.util.Exceptions;
import org.postgresql.util.PSQLException;
import vrframework.classe.ProgressBar;
import vrimplantacao2_5.conversor.services.BancoDeDadosDBFService;

/**
 *
 * @author Desenvolvimento
 */
public class ConversorDbfGUI extends javax.swing.JFrame {

    File[] filesDBF = null;
    File[] filesMemo = null;
    BancoDeDadosDBFService service;
    boolean haMemoFiles = false;

    /**
     * Creates new form ConversorDbfGUI
     */
    public ConversorDbfGUI() {
        this.service = new BancoDeDadosDBFService();
        try {
            service.criarControleDeDadosConvertidos();
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
            System.out.println(ex.getMessage());
        }
        initComponents();
        setLocationRelativeTo(null);
        jFileChooserDBF.setPreferredSize(new Dimension(528, 326));
        lblLogo.setText("");
        lblLogo.setSize(800, 800);
        setExtendedState(MAXIMIZED_BOTH);
        jFileChooserDBF.setMultiSelectionEnabled(true);
        jPanel5.setVisible(true);
        jFileChooserDBF.setVisible(false);
        labelResultado.setVisible(false);
        jTxInstrucaoTexto.setEditable(false);
        jTxInstrucaoTexto.setCaretPosition(0);
        btnReabriDBF.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextNomeBanco = new javax.swing.JTextField();
        labelResultado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jButtoncarregarMemo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxInstrucaoTexto = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jButtonConverter = new javax.swing.JButton();
        btnReabriDBF = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jFileChooserDBF = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ConversorDbfGUI.class, "ConversorDbfGUI.jLabel1.text")); // NOI18N

        jTextNomeBanco.setText(org.openide.util.NbBundle.getMessage(ConversorDbfGUI.class, "ConversorDbfGUI.jTextNomeBanco.text")); // NOI18N

        labelResultado.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(labelResultado, org.openide.util.NbBundle.getMessage(ConversorDbfGUI.class, "ConversorDbfGUI.labelResultado.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(ConversorDbfGUI.class, "ConversorDbfGUI.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(ConversorDbfGUI.class, "ConversorDbfGUI.jLabel2.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextNomeBanco)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 144, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(labelResultado))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNomeBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(labelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(204, 0, 0));
        org.openide.awt.Mnemonics.setLocalizedText(lblTitulo, org.openide.util.NbBundle.getMessage(ConversorDbfGUI.class, "ConversorDbfGUI.lblTitulo.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButtoncarregarMemo, org.openide.util.NbBundle.getMessage(ConversorDbfGUI.class, "ConversorDbfGUI.jButtoncarregarMemo.text")); // NOI18N
        jButtoncarregarMemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncarregarMemoActionPerformed(evt);
            }
        });

        jTxInstrucaoTexto.setColumns(20);
        jTxInstrucaoTexto.setRows(5);
        jTxInstrucaoTexto.setText(org.openide.util.NbBundle.getMessage(ConversorDbfGUI.class, "ConversorDbfGUI.jTxInstrucaoTexto.text")); // NOI18N
        jScrollPane1.setViewportView(jTxInstrucaoTexto);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtoncarregarMemo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtoncarregarMemo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonConverter.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButtonConverter, org.openide.util.NbBundle.getMessage(ConversorDbfGUI.class, "ConversorDbfGUI.jButtonConverter.text")); // NOI18N
        jButtonConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConverterActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnReabriDBF, org.openide.util.NbBundle.getMessage(ConversorDbfGUI.class, "ConversorDbfGUI.btnReabriDBF.text")); // NOI18N
        btnReabriDBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReabriDBFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReabriDBF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonConverter, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConverter, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReabriDBF))
                .addContainerGap())
        );

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vrimplantacao2_5/nutricional/utils/logoVr.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lblLogo, org.openide.util.NbBundle.getMessage(ConversorDbfGUI.class, "ConversorDbfGUI.lblLogo.text")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 399, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ConversorDbfGUI.class, "ConversorDbfGUI.jPanel5.border.title"))); // NOI18N

        jFileChooserDBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooserDBFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooserDBF, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooserDBF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (validaNomeBanco()) {
            service.setNomeBanco(jTextNomeBanco.getText());
            Thread thread = new Thread() {
                @Override
                public void run() {
                    try {
                        ProgressBar.show();
                        ProgressBar.setCancel(false);
                        ProgressBar.setStatus("Criando o banco, por favor aguarde.");
                        criarBanco();
                        ProgressBar.dispose();
                        jFileChooserDBF.setVisible(true);
                    } catch (Exception ex) {
                        System.out.println(ex.getMessage());
                        ProgressBar.dispose();
                        Exceptions.printStackTrace(ex);
                    }
                }
            };
            thread.start();
        }
        labelResultado.setText("Dados de Conversão do banco: " + jTextNomeBanco.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jFileChooserDBFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooserDBFActionPerformed
        if (evt.getActionCommand().equals(javax.swing.JFileChooser.CANCEL_SELECTION)) {
            this.dispose();
        } else {
            carregarArquivosDBF();
            jFileChooserDBF.setVisible(false);
            piscarBotao();
            btnReabriDBF.setVisible(true);
        }
    }//GEN-LAST:event_jFileChooserDBFActionPerformed

    private void jButtonConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConverterActionPerformed
        if (filesDBF != null) {
            salvar();
        } else {
            JOptionPane.showMessageDialog(null, "Você esqueceu de selecionar os arquivos DBF", "ops!", 1);
        };
    }//GEN-LAST:event_jButtonConverterActionPerformed

    private void jButtoncarregarMemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncarregarMemoActionPerformed
        JFileChooser jFileChooserMemo = new JFileChooser();
        jFileChooserMemo.setDialogTitle("Carregar Memo Files");
        jFileChooserMemo.setPreferredSize(new Dimension(500, 450));
        jFileChooserMemo.setMultiSelectionEnabled(true);
        int resultado = jFileChooserMemo.showOpenDialog(this);
        if (resultado == JFileChooser.CANCEL_OPTION) {
            jFileChooserMemo.setVisible(false);
            this.filesMemo = null;
        } else {
            this.filesMemo = jFileChooserMemo.getSelectedFiles();
            haMemoFiles = true;
            jFileChooserMemo.setVisible(false);
        }
    }//GEN-LAST:event_jButtoncarregarMemoActionPerformed

    private void btnReabriDBFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReabriDBFActionPerformed
        jFileChooserDBF.setVisible(true);
        this.filesDBF = null;
        jFileChooserDBF.setSelectedFiles(filesDBF);
        btnReabriDBF.setVisible(false);
    }//GEN-LAST:event_btnReabriDBFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorDbfGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorDbfGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorDbfGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorDbfGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorDbfGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReabriDBF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonConverter;
    private javax.swing.JButton jButtoncarregarMemo;
    private javax.swing.JFileChooser jFileChooserDBF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextNomeBanco;
    private javax.swing.JTextArea jTxInstrucaoTexto;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables

    public void criarBanco() {
        try {
            BancoDeDadosDBFService.criarBanco();
            ProgressBar.dispose();
            labelResultado.setText("<html> <font size=\"2\" color=blue >Banco de Dados criado com sucesso</font></html>");
            labelResultado.setVisible(true);
        } catch (PSQLException ex) {
            labelResultado.setText("<html> <font size=\"2\" color=red>Banco de Dados que você digitou provavelmente já existe.</font></html>");
            labelResultado.setVisible(true);
            ProgressBar.dispose();
            ex.printStackTrace();
        } catch (Exception ex) {
            labelResultado.setText("<html> <font size=\"2\" color=red >Houve algum erro. Contate o setor de Migração</font></html>");
            labelResultado.setVisible(true);
            ProgressBar.dispose();
            Exceptions.printStackTrace(ex);
        }
    }

    public boolean validaNomeBanco() {
        if ("".equals(jTextNomeBanco.getText()) || jTextNomeBanco.getText() == null) {
            JOptionPane.showMessageDialog(this, "Você precisa digitar um nome válido para o banco. \n\n"
                    + "Exemplo: NOME_DO_BANCO, NOME_DO_BANCO_10.");
            jTextNomeBanco.grabFocus();
            return false;
        } else {
            return true;
        }
    }

    private void salvar() {
        BancoDeDadosDBFService.salvar(filesDBF, filesMemo, haMemoFiles);
    }

    private void carregarArquivosDBF() {
        filesDBF = jFileChooserDBF.getSelectedFiles();
    }

    private void piscarBotao() {
        Thread thread = new Thread() {
            @Override
            public void run() {
                try {
                    Color corOriginal = jButtonConverter.getBackground();
                    Color corOriginalF = jButtonConverter.getForeground();
                    Thread.sleep(300);
                    jButtonConverter.setForeground(new Color(255, 103, 0));
                    jButtonConverter.setBackground(Color.BLACK);
                    Thread.sleep(300);
                    jButtonConverter.setBackground(corOriginal);
                    jButtonConverter.setForeground(corOriginalF);
                    Thread.sleep(300);
                    jButtonConverter.setForeground(new Color(255, 103, 0));
                    jButtonConverter.setBackground(Color.BLACK);
                    Thread.sleep(300);
                    jButtonConverter.setBackground(corOriginal);
                    jButtonConverter.setForeground(corOriginalF);
                    Thread.sleep(300);
                    jButtonConverter.setForeground(new Color(255, 103, 0));
                    jButtonConverter.setBackground(Color.BLACK);
                    Thread.sleep(300);
                    jButtonConverter.setBackground(corOriginal);
                    jButtonConverter.setForeground(corOriginalF);
                    Thread.sleep(300);
                    jButtonConverter.setForeground(new Color(255, 103, 0));
                    jButtonConverter.setBackground(Color.BLACK);
                    Thread.sleep(300);
                    jButtonConverter.setBackground(corOriginal);
                    jButtonConverter.setForeground(corOriginalF);

                } catch (Exception ex) {
                    System.out.println(ex.getMessage());
                }
            }
        };
        thread.start();
    }
}
