package vrimplantacao2.gui.component.mapareformatributaria.cst;

import java.util.List;
import java.awt.Frame;
import java.awt.Dimension;
import javax.swing.JDialog;
import java.util.ArrayList;
import java.awt.event.KeyEvent;
import vrframework.classe.Util;
import java.awt.event.MouseEvent;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import org.openide.util.Exceptions;
import vrimplantacao2.vo.enums.Cst;
import java.awt.event.MouseListener;
import vrframework.bean.table.VRColumnTable;

/**
 *
 * @author Wesley
 */
public class MapaReformaTributariaCstView extends JDialog {
    
    private MapaReformaTributariaCstController controller = new MapaReformaTributariaCstController(this);

    public MapaReformaTributariaCstController getController() {
        return controller;
    }

    public String getSistema() {
        return controller.getSistema();
    }

    public void setSistema(String sistema) {
        controller.setSistema(sistema);
        txtSistema.setText(sistema);
    }

    public String getLoja() {
        return controller.getLoja();
    }

    public void setLoja(String loja) {
        controller.setLoja(loja);
        txtAgrupador.setText(loja);
    }

    public void setProvider(MapaReformaTributariaCstProvider provider) {
        controller.setProvider(provider);
    }

    public MapaReformaTributariaCstProvider getProvider() {
        return controller.getProvider();
    }
    
    /**
     * Creates new form MapaTributacaoPanel
     */
    public MapaReformaTributariaCstView() {
        super();
        initComponents();
        tblVR.tblTabela.addMouseListener(
                new MouseListener() {

                    @Override
                    public void mouseClicked(MouseEvent e) {
                        if (e.getClickCount() == 2) {
                            e.consume();
                            try {
                                
                                controller.gravarCst();
                            } catch (Exception ex) {
                                Exceptions.printStackTrace(ex);
                                throw new RuntimeException(ex);
                            }
                        }
                    }

                    @Override
                    public void mousePressed(MouseEvent e) {
                        
                    }

                    @Override
                    public void mouseReleased(MouseEvent e) {
                        
                    }

                    @Override
                    public void mouseEntered(MouseEvent e) {
                        
                    }

                    @Override
                    public void mouseExited(MouseEvent e) {
                        
                    }
                }
        );
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        tblVR = new vrframework.bean.tableEx.VRTableEx();
        jCheckBox1 = new javax.swing.JCheckBox();
        tblMapa = new vrframework.bean.tableEx.VRTableEx();
        jLabel1 = new javax.swing.JLabel();
        txtSistema = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAgrupador = new javax.swing.JTextField();
        btnIncluir = new javax.swing.JButton();
        btnIncluirtodas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("\"Mapa de Reforma Tributaria - CST\"");
        setModal(true);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, "Buscar por CST");

        txtBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaKeyRelesed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnAtualizar, "Atualizar listagem");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarOnClick(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox1, "Exibir todos");

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, "Sistema");

        txtSistema.setEditable(false);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, "Loja");

        txtAgrupador.setEditable(false);

        org.openide.awt.Mnemonics.setLocalizedText(btnIncluir, "Incluir CST - F2");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirOnClick(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnIncluirtodas, "Incluir Todas as CSTs - F3");
        btnIncluirtodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirtodasOnClick(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tblVR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIncluirtodas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAtualizar))
                    .addComponent(tblMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtSistema))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtAgrupador, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizar)
                    .addComponent(btnIncluir)
                    .addComponent(btnIncluirtodas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblVR, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblMapa, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAgrupador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarOnClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarOnClick
        try {
            controller.atualizarMapa();
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
            Util.exibirMensagemErro(ex, "");            
        }
    }//GEN-LAST:event_btnAtualizarOnClick

    public static void exibir(Frame mdiFrame, String sistema, String loja, MapaReformaTributariaCstProvider provider) throws Exception {
        MapaReformaTributariaCstView view = new MapaReformaTributariaCstView();
        view.setSistema(sistema);
        view.setLoja(loja);
        view.setProvider(provider);
        
        view.controller.atualizarMapa();
        
        view.setPreferredSize(new Dimension(1200, 600));
        view.pack();

        Dimension ds = mdiFrame.getSize();
        Dimension dw = view.getSize();

        int x = (ds.width - dw.width) / 2;
        int y = (ds.height - dw.height) / 2;

        if (x < 0) {
            x = 0;
        }

        if (y < 0) {
            y = 0;
        }

        view.setLocation(x, y);
        view.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        view.setVisible(true);
    }
    
    private void btnIncluirOnClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirOnClick
        controller.incluirCst();
        
        try {
            controller.atualizarMapa();
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
            Util.exibirMensagemErro(ex, "");            
        }
    }//GEN-LAST:event_btnIncluirOnClick

    private void btnIncluirtodasOnClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirtodasOnClick
        controller.incluirTodasCst();
        
        try {
            controller.atualizarMapa();
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
            Util.exibirMensagemErro(ex, "");            
        }
    }//GEN-LAST:event_btnIncluirtodasOnClick

    private void txtBuscaKeyRelesed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaKeyRelesed
        try {
            int keyCode = evt.getKeyCode();
            evt.consume();
            if (keyCode == KeyEvent.VK_ENTER) {
                txtBusca.selectAll();
                controller.gravarCst();
            } else if (keyCode == KeyEvent.VK_DOWN) {
                controller.nextTributVR();
            } else if (keyCode == KeyEvent.VK_UP) {
                controller.previousTributVR();
            } else if (keyCode == KeyEvent.VK_ESCAPE) {
                this.setVisible(false);
            } else if (keyCode == KeyEvent.VK_F2) {
                btnIncluir.doClick();
            } else if (keyCode == KeyEvent.VK_F3) {
                btnIncluirtodas.doClick();
            } else {

                String texto = txtBusca.getText().replaceAll("\\D", "");

                if (texto.length() > 3) {
                    texto = texto.substring(0, 3);
                    txtBusca.setText(texto);
                }

                controller.buscar(texto);
            }
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
            Util.exibirMensagemErro(ex, "");
        }
    }//GEN-LAST:event_txtBuscaKeyRelesed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btnAtualizar;
    javax.swing.JButton btnIncluir;
    javax.swing.JButton btnIncluirtodas;
    javax.swing.JCheckBox jCheckBox1;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    vrframework.bean.tableEx.VRTableEx tblMapa;
    vrframework.bean.tableEx.VRTableEx tblVR;
    javax.swing.JTextField txtAgrupador;
    javax.swing.JTextField txtBusca;
    javax.swing.JTextField txtSistema;
    // End of variables declaration//GEN-END:variables

    void refresh() throws Exception {
        List<VRColumnTable> vColunaProduto = new ArrayList();
        vColunaProduto.add(new VRColumnTable("Código Ant.", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("CST Ant.", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("Descrição Ant.", true, SwingConstants.LEFT, false, null));
        vColunaProduto.add(new VRColumnTable("ibs/cbs Ant.", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("Red. Ant", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("Dif. Ant", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("Trib. Reg. Ant", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("ibs/cbs mono Ant", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable(" - - ", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("Cód. VR", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("CST VR", true, SwingConstants.CENTER, false, null));      
        vColunaProduto.add(new VRColumnTable("Descrição VR", true, SwingConstants.LEFT, false, null));
        vColunaProduto.add(new VRColumnTable("ibs/cbs VR", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("Red. VR", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("Dif. VR", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("Trib. Reg. VR", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("ibs/cbs mono VR", true, SwingConstants.CENTER, false, null));
        tblMapa.configurarColuna(vColunaProduto, this, "Mapa", "mapaTributacoes");
        
        Object[][] dados = new Object[controller.getMapa().size()][tblMapa.getvColuna().size()];
        int i = 0;
        for (MapaReformaTributariaCstVO row: controller.getMapa()) {
            
            dados[i][0] = row.getOrigId();
            dados[i][1] = String.format("%03d", row.getOrigCst());
            dados[i][2] = row.getOrigDescricao();
            dados[i][3] = row.isGrupoIbsCbs() ? "S" : "";
            dados[i][4] = row.isGrupoReducao() ? "S" : "";
            dados[i][5] = row.isGrupoDiferimento() ? "S" : "";
            dados[i][6] = row.isGrupoTribRegular() ? "S" : "";
            dados[i][7] = row.isGrupoIbsCbsMono() ? "S" : "";
            dados[i][8] = " >>>> ";
            if (row.getCst()== null) {
                dados[i][9] = "";
                dados[i][10] = "";
                dados[i][11] = "";
                dados[i][12] = "";
                dados[i][13] = "";
                dados[i][14] = "";
                dados[i][15] = "";
                dados[i][16] = "";
            } else {

                dados[i][9] = row.getCst().getId();
                dados[i][10] = String.format("%03d", row.getCst().getCst());
                dados[i][11] = row.getCst().getDescricao();
                dados[i][12] = row.getCst().isGrupoibscbs() ? "S" : "";
                dados[i][13] = row.getCst().isGruporeducao() ? "S" : "";
                dados[i][14] = row.getCst().isGrupodiferimento() ? "S" : "";
                dados[i][15] = row.getCst().isGrupotribregular() ? "S" : "";
                dados[i][16] = row.getCst().isGrupoibscbsmono() ? "S" : "";
            }
            i++;
        }          

        tblMapa.setModel(dados);
        tblMapa.setRowHeight(30);
        tblMapa.atualizarTamanhoColuna();
        if (tblMapa.getRowCount() > 0) {
            tblMapa.setLinhaSelecionada(0);
        }
    }

    void refreshBusca() throws Exception {
        List<VRColumnTable> vColunaProduto = new ArrayList();      
        vColunaProduto.add(new VRColumnTable("Cód. VR", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("CST - VR", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("Descrição - VR", true, SwingConstants.LEFT, false, null));
        vColunaProduto.add(new VRColumnTable("Ibs/Cbs.", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("Redução.", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("Diferimento", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("Trib. Regular", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("Ibs/Cbs mono.", true, SwingConstants.CENTER, false, null));
        tblVR.configurarColuna(vColunaProduto, this, "CST", "csts");
        
        Object[][] dados = new Object[controller.getCstsVR().size()][tblVR.getvColuna().size()];
        int i = 0;
        for (Cst cst: controller.getCstsVR()) {
            
            dados[i][0] = cst.getId();
            dados[i][1] = String.format("%03d", cst.getCst());
            dados[i][2] = cst.getDescricao();
            dados[i][3] = cst.isGrupoibscbs() ? "S" : "";
            dados[i][4] = cst.isGruporeducao() ? "S" : "";
            dados[i][5] = cst.isGrupodiferimento() ? "S" : "";
            dados[i][6] = cst.isGrupotribregular() ? "S" : "";
            dados[i][7] = cst.isGrupoibscbsmono() ? "S" : "";
            
            i++;
        }            

        tblVR.setModel(dados);
        tblVR.setRowHeight(30);
        tblVR.atualizarTamanhoColuna();
        if (tblVR.getRowCount() > 0) {
            tblVR.setLinhaSelecionada(0);
        }
    }
}
