/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vrimplantacao2.gui.component;

import java.awt.Container;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import javax.swing.JDialog;
import javax.swing.WindowConstants;

/**
 *
 * @author Leandro
 */
public class CustomFrame extends javax.swing.JDialog {

    public CustomFrame(Frame mdiFrame, String titulo, boolean modal) {
        super(mdiFrame, titulo, modal);
    }
    
    protected void centralizarForm() throws Exception {
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dw = this.getSize();

        setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }
    
    public static JDialog exibir(Frame mdiFrame, String titulo, boolean modal, Container view, int width, int lenght) throws Exception {
        CustomFrame frame = new CustomFrame(mdiFrame, titulo, modal);
        
        
        frame.setContentPane(view);
        frame.setPreferredSize(new Dimension(width, lenght));
        frame.pack();
        
        frame.centralizarForm();

        /*if (mdiFrame != null) {
            
            Dimension ds = mdiFrame.getSize();
            Dimension dw = frame.getSize();

            int x = (ds.width - dw.width) / 2;
            int y = (ds.height - dw.height) / 3;

            if (x < 0) {
                x = 0;
            }

            if (y < 0) {
                y = 0;
            }

            frame.setLocation(x, y);
            
        }*/

        frame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        return frame;
    }

    /**
     * Creates new form CustomFrame
     */
    public CustomFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
