/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vrimplantacao2.gui.component.importpanel.produto;

/**
 *
 * @author Leandro
 */
public class ProdutoImportView extends javax.swing.JPanel {

    /**
     * Creates new form ProdutoImportView
     */
    public ProdutoImportView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkMercadologico = new vrframework.bean.checkBox.VRCheckBox();
        chkFamiliaProduto = new vrframework.bean.checkBox.VRCheckBox();
        vRPanel1 = new vrframework.bean.panel.VRPanel();
        chkProdutos = new vrframework.bean.checkBox.VRCheckBox();
        chkManterBalanca = new vrframework.bean.checkBox.VRCheckBox();
        chkT1Custo = new vrframework.bean.checkBox.VRCheckBox();
        chkCustoSemImposto = new vrframework.bean.checkBox.VRCheckBox();
        chkCustoComImposto = new vrframework.bean.checkBox.VRCheckBox();
        chkT1Preco = new vrframework.bean.checkBox.VRCheckBox();
        chkT1Estoque = new vrframework.bean.checkBox.VRCheckBox();
        chkT1EAN = new vrframework.bean.checkBox.VRCheckBox();
        chkT1EANemBranco = new vrframework.bean.checkBox.VRCheckBox();
        chkT1PisCofins = new vrframework.bean.checkBox.VRCheckBox();
        chkT1NatReceita = new vrframework.bean.checkBox.VRCheckBox();
        chkT1ICMS = new vrframework.bean.checkBox.VRCheckBox();
        chkT1AtivoInativo = new vrframework.bean.checkBox.VRCheckBox();
        chkT1DescCompleta = new vrframework.bean.checkBox.VRCheckBox();
        chkT1DescReduzida = new vrframework.bean.checkBox.VRCheckBox();
        chkT1DescGondola = new vrframework.bean.checkBox.VRCheckBox();
        chkT1ProdMercadologico = new vrframework.bean.checkBox.VRCheckBox();
        chkValidade = new vrframework.bean.checkBox.VRCheckBox();
        chkFamilia = new vrframework.bean.checkBox.VRCheckBox();
        chkTipoEmbalagemEAN = new vrframework.bean.checkBox.VRCheckBox();
        chkQtdEmbalagemEAN = new vrframework.bean.checkBox.VRCheckBox();
        chkQtdEmbalagemEAN1 = new vrframework.bean.checkBox.VRCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(chkMercadologico, org.openide.util.NbBundle.getMessage(ProdutoImportView.class, "ProdutoImportView.chkMercadologico.text")); // NOI18N
        chkMercadologico.setEnabled(true);
        add(chkMercadologico);

        org.openide.awt.Mnemonics.setLocalizedText(chkFamiliaProduto, org.openide.util.NbBundle.getMessage(ProdutoImportView.class, "ProdutoImportView.chkFamiliaProduto.text")); // NOI18N
        chkFamiliaProduto.setEnabled(true);
        chkFamiliaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFamiliaProdutoActionPerformed(evt);
            }
        });
        add(chkFamiliaProduto);

        org.openide.awt.Mnemonics.setLocalizedText(chkProdutos, org.openide.util.NbBundle.getMessage(ProdutoImportView.class, "ProdutoImportView.chkProdutos.text")); // NOI18N
        chkProdutos.setEnabled(true);

        org.openide.awt.Mnemonics.setLocalizedText(chkManterBalanca, org.openide.util.NbBundle.getMessage(ProdutoImportView.class, "ProdutoImportView.chkManterBalanca.text")); // NOI18N
        chkManterBalanca.setEnabled(true);

        javax.swing.GroupLayout vRPanel1Layout = new javax.swing.GroupLayout(vRPanel1);
        vRPanel1.setLayout(vRPanel1Layout);
        vRPanel1Layout.setHorizontalGroup(
            vRPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vRPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(chkProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkManterBalanca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        vRPanel1Layout.setVerticalGroup(
            vRPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vRPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(vRPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkManterBalanca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        add(vRPanel1);

        org.openide.awt.Mnemonics.setLocalizedText(chkT1Custo, org.openide.util.NbBundle.getMessage(ProdutoImportView.class, "ProdutoImportView.chkT1Custo.text")); // NOI18N
        add(chkT1Custo);

        org.openide.awt.Mnemonics.setLocalizedText(chkCustoSemImposto, org.openide.util.NbBundle.getMessage(ProdutoImportView.class, "ProdutoImportView.chkCustoSemImposto.text")); // NOI18N
        add(chkCustoSemImposto);

        org.openide.awt.Mnemonics.setLocalizedText(chkCustoComImposto, org.openide.util.NbBundle.getMessage(ProdutoImportView.class, "ProdutoImportView.chkCustoComImposto.text")); // NOI18N
        add(chkCustoComImposto);

        org.openide.awt.Mnemonics.setLocalizedText(chkT1Preco, org.openide.util.NbBundle.getMessage(ProdutoImportView.class, "ProdutoImportView.chkT1Preco.text")); // NOI18N
        add(chkT1Preco);

        org.openide.awt.Mnemonics.setLocalizedText(chkT1Estoque, org.openide.util.NbBundle.getMessage(ProdutoImportView.class, "ProdutoImportView.chkT1Estoque.text")); // NOI18N
        add(chkT1Estoque);

        org.openide.awt.Mnemonics.setLocalizedText(chkT1EAN, org.openide.util.NbBundle.getMessage(ProdutoImportView.class, "ProdutoImportView.chkT1EAN.text")); // NOI18N
        add(chkT1EAN);

        org.openide.awt.Mnemonics.setLocalizedText(chkT1EANemBranco, org.openide.util.NbBundle.getMessage(ProdutoImportView.class, "ProdutoImportView.chkT1EANemBranco.text")); // NOI18N
        add(chkT1EANemBranco);

        org.openide.awt.Mnemonics.setLocalizedText(chkT1PisCofins, org.openide.util.NbBundle.getMessage(ProdutoImportView.class, "ProdutoImportView.chkT1PisCofins.text")); // NOI18N
        add(chkT1PisCofins);

        org.openide.awt.Mnemonics.setLocalizedText(chkT1NatReceita, org.openide.util.NbBundle.getMessage(ProdutoImportView.class, "ProdutoImportView.chkT1NatReceita.text")); // NOI18N
        add(chkT1NatReceita);

        org.openide.awt.Mnemonics.setLocalizedText(chkT1ICMS, org.openide.util.NbBundle.getMessage(ProdutoImportView.class, "ProdutoImportView.chkT1ICMS.text")); // NOI18N
        add(chkT1ICMS);

        org.openide.awt.Mnemonics.setLocalizedText(chkT1AtivoInativo, org.openide.util.NbBundle.getMessage(ProdutoImportView.class, "ProdutoImportView.chkT1AtivoInativo.text")); // NOI18N
        add(chkT1AtivoInativo);

        org.openide.awt.Mnemonics.setLocalizedText(chkT1DescCompleta, org.openide.util.NbBundle.getMessage(ProdutoImportView.class, "ProdutoImportView.chkT1DescCompleta.text")); // NOI18N
        add(chkT1DescCompleta);

        org.openide.awt.Mnemonics.setLocalizedText(chkT1DescReduzida, org.openide.util.NbBundle.getMessage(ProdutoImportView.class, "ProdutoImportView.chkT1DescReduzida.text")); // NOI18N
        add(chkT1DescReduzida);

        org.openide.awt.Mnemonics.setLocalizedText(chkT1DescGondola, org.openide.util.NbBundle.getMessage(ProdutoImportView.class, "ProdutoImportView.chkT1DescGondola.text")); // NOI18N
        add(chkT1DescGondola);

        org.openide.awt.Mnemonics.setLocalizedText(chkT1ProdMercadologico, org.openide.util.NbBundle.getMessage(ProdutoImportView.class, "ProdutoImportView.chkT1ProdMercadologico.text")); // NOI18N
        add(chkT1ProdMercadologico);

        org.openide.awt.Mnemonics.setLocalizedText(chkValidade, org.openide.util.NbBundle.getMessage(ProdutoImportView.class, "ProdutoImportView.chkValidade.text")); // NOI18N
        add(chkValidade);

        org.openide.awt.Mnemonics.setLocalizedText(chkFamilia, org.openide.util.NbBundle.getMessage(ProdutoImportView.class, "ProdutoImportView.chkFamilia.text")); // NOI18N
        chkFamilia.setToolTipText(org.openide.util.NbBundle.getMessage(ProdutoImportView.class, "ProdutoImportView.chkFamilia.toolTipText")); // NOI18N
        add(chkFamilia);

        org.openide.awt.Mnemonics.setLocalizedText(chkTipoEmbalagemEAN, org.openide.util.NbBundle.getMessage(ProdutoImportView.class, "ProdutoImportView.chkTipoEmbalagemEAN.text")); // NOI18N
        add(chkTipoEmbalagemEAN);

        org.openide.awt.Mnemonics.setLocalizedText(chkQtdEmbalagemEAN, org.openide.util.NbBundle.getMessage(ProdutoImportView.class, "ProdutoImportView.chkQtdEmbalagemEAN.text")); // NOI18N
        add(chkQtdEmbalagemEAN);

        org.openide.awt.Mnemonics.setLocalizedText(chkQtdEmbalagemEAN1, org.openide.util.NbBundle.getMessage(ProdutoImportView.class, "ProdutoImportView.chkQtdEmbalagemEAN1.text")); // NOI18N
        add(chkQtdEmbalagemEAN1);
    }// </editor-fold>//GEN-END:initComponents

    private void chkFamiliaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFamiliaProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkFamiliaProdutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vrframework.bean.checkBox.VRCheckBox chkCustoComImposto;
    private vrframework.bean.checkBox.VRCheckBox chkCustoSemImposto;
    private vrframework.bean.checkBox.VRCheckBox chkFamilia;
    private vrframework.bean.checkBox.VRCheckBox chkFamiliaProduto;
    private vrframework.bean.checkBox.VRCheckBox chkManterBalanca;
    private vrframework.bean.checkBox.VRCheckBox chkMercadologico;
    private vrframework.bean.checkBox.VRCheckBox chkProdutos;
    private vrframework.bean.checkBox.VRCheckBox chkQtdEmbalagemEAN;
    private vrframework.bean.checkBox.VRCheckBox chkQtdEmbalagemEAN1;
    private vrframework.bean.checkBox.VRCheckBox chkT1AtivoInativo;
    private vrframework.bean.checkBox.VRCheckBox chkT1Custo;
    private vrframework.bean.checkBox.VRCheckBox chkT1DescCompleta;
    private vrframework.bean.checkBox.VRCheckBox chkT1DescGondola;
    private vrframework.bean.checkBox.VRCheckBox chkT1DescReduzida;
    private vrframework.bean.checkBox.VRCheckBox chkT1EAN;
    private vrframework.bean.checkBox.VRCheckBox chkT1EANemBranco;
    private vrframework.bean.checkBox.VRCheckBox chkT1Estoque;
    private vrframework.bean.checkBox.VRCheckBox chkT1ICMS;
    private vrframework.bean.checkBox.VRCheckBox chkT1NatReceita;
    private vrframework.bean.checkBox.VRCheckBox chkT1PisCofins;
    private vrframework.bean.checkBox.VRCheckBox chkT1Preco;
    private vrframework.bean.checkBox.VRCheckBox chkT1ProdMercadologico;
    private vrframework.bean.checkBox.VRCheckBox chkTipoEmbalagemEAN;
    private vrframework.bean.checkBox.VRCheckBox chkValidade;
    private vrframework.bean.panel.VRPanel vRPanel1;
    // End of variables declaration//GEN-END:variables
}
