package vrimplantacao2.gui.component.mapareformatributaria.classificacaotributariancm;

import java.util.List;
import java.awt.Frame;
import java.awt.Dimension;
import javax.swing.JDialog;
import java.util.ArrayList;
import java.awt.event.KeyEvent;
import vrframework.classe.Util;
import java.awt.event.MouseEvent;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import org.openide.util.Exceptions;
import java.awt.event.MouseListener;
import vrframework.bean.table.VRColumnTable;
import vrimplantacao2.vo.enums.ClassificacaoTributariaNcm;
import vrimplantacao2.gui.component.mapareformatributaria.MapaReformaTributariaProvider;
import vrimplantacao2.vo.enums.NcmVO;

/**
 *
 * @author Wesley
 */
public class MapaReformaTributariaClassificacaoNcmView extends JDialog {

    private MapaReformaTributariaClassificacaoNcmController controller = new MapaReformaTributariaClassificacaoNcmController(this);

    public MapaReformaTributariaClassificacaoNcmController getController() {
        return controller;
    }

    public String getSistema() {
        return controller.getSistema();
    }

    public void setSistema(String sistema) {
        controller.setSistema(sistema);
        txtSistema.setText(sistema);
    }

    public void setLoja(String loja) {
        controller.setLoja(loja);
        txtAgrupador.setText(loja);
    }

    public void setLojaVR(int lojaVR) {
        controller.setLojaVR(lojaVR);
    }

    public void setProvider(MapaReformaTributariaProvider provider) {
        controller.setProvider(provider);
    }

    public MapaReformaTributariaProvider getProvider() {
        return controller.getProvider();
    }

    public void setMapaClassificacao() {
        try {
            controller.setMapaClassificacao();
        } catch (Exception e) {
            System.err.println("Erro ao carregar o mapa de CST");
        }
    }

    /**
     * Creates new form MapaTributacaoPanel
     */
    public MapaReformaTributariaClassificacaoNcmView() {
        super();
        initComponents();
        btnIncluir.setVisible(false);
        tblVR.tblTabela.addMouseListener(
                new MouseListener() {

            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    e.consume();
                    try {

//                        controller.gravarClassificacaoNcm();
                    } catch (Exception ex) {
                        Exceptions.printStackTrace(ex);
                        throw new RuntimeException(ex);
                    }
                }
            }

            @Override
            public void mousePressed(MouseEvent e) {

            }

            @Override
            public void mouseReleased(MouseEvent e) {

            }

            @Override
            public void mouseEntered(MouseEvent e) {

            }

            @Override
            public void mouseExited(MouseEvent e) {

            }
        }
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        classBuscaNcm1 = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        tblVR = new vrframework.bean.tableEx.VRTableEx();
        CknExibirTodos = new javax.swing.JCheckBox();
        tblMapa = new vrframework.bean.tableEx.VRTableEx();
        jLabel1 = new javax.swing.JLabel();
        txtSistema = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAgrupador = new javax.swing.JTextField();
        btnIncluir = new javax.swing.JButton();
        btnIncluirtodas = new javax.swing.JButton();
        classBuscaNcm2 = new javax.swing.JTextField();
        classBuscaNcm3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("\"Mapa de Reforma Tributaria - CST\"");
        setModal(true);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, "Ncm 1");

        classBuscaNcm1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                classBuscaNcm1KeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                classBuscaNcm1KeyRelesed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnAtualizar, "Atualizar listagem");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarOnClick(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(CknExibirTodos, "Exibir todos");
        CknExibirTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CknExibirTodosActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, "Sistema");

        txtSistema.setEditable(false);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, "Loja");

        txtAgrupador.setEditable(false);

        org.openide.awt.Mnemonics.setLocalizedText(btnIncluir, "Incluir Classificação NCM - F2");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirOnClick(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnIncluirtodas, "Incluir Todas - F3");
        btnIncluirtodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirtodasOnClick(evt);
            }
        });

        classBuscaNcm2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                classBuscaNcm2KeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                classBuscaNcm2KeyRelesed(evt);
            }
        });

        classBuscaNcm3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                classBuscaNcm3KeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                classBuscaNcm3KeyRelesed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, "Ncm 2");

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, "Ncm 3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tblVR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtSistema))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtAgrupador, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CknExibirTodos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(classBuscaNcm1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(classBuscaNcm2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(classBuscaNcm3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIncluirtodas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(btnAtualizar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classBuscaNcm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizar)
                    .addComponent(btnIncluir)
                    .addComponent(btnIncluirtodas)
                    .addComponent(classBuscaNcm2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classBuscaNcm3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblVR, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CknExibirTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblMapa, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAgrupador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarOnClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarOnClick
        try {
            controller.atualizarMapa();
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
            Util.exibirMensagemErro(ex, "");
        }
    }//GEN-LAST:event_btnAtualizarOnClick

    public static void exibir(Frame mdiFrame, String sistema, String loja, MapaReformaTributariaProvider provider, int lojaVR) throws Exception {
        MapaReformaTributariaClassificacaoNcmView view = new MapaReformaTributariaClassificacaoNcmView();
        view.setSistema(sistema);
        view.setLoja(loja);
        view.setProvider(provider);
        view.setMapaClassificacao();
        view.setLojaVR(lojaVR);

        view.controller.atualizarMapa();

        view.setPreferredSize(new Dimension(1200, 600));
        view.pack();

        Dimension ds = mdiFrame.getSize();
        Dimension dw = view.getSize();

        int x = (ds.width - dw.width) / 2;
        int y = (ds.height - dw.height) / 2;

        if (x < 0) {
            x = 0;
        }

        if (y < 0) {
            y = 0;
        }

        view.setLocation(x, y);
        view.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        view.setVisible(true);
    }

    private void btnIncluirOnClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirOnClick

        try {
//            controller.incluirClassificacaoNcm();
            controller.atualizarMapa();
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
            Util.exibirMensagemErro(ex, "");
        }
    }//GEN-LAST:event_btnIncluirOnClick

    private void btnIncluirtodasOnClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirtodasOnClick
        controller.incluirTodasClassificacoesNcm();

        try {
            controller.atualizarMapa();
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
            Util.exibirMensagemErro(ex, "");
        }
    }//GEN-LAST:event_btnIncluirtodasOnClick

    private void classBuscaNcm1KeyRelesed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_classBuscaNcm1KeyRelesed
        try {
            int keyCode = evt.getKeyCode();
            if (keyCode == KeyEvent.VK_ENTER) {
                classBuscaNcm1.selectAll();
//                controller.gravarClassificacaoNcm();
            } else if (keyCode == KeyEvent.VK_DOWN) {
                evt.consume();
                controller.nextTributVR();
            } else if (keyCode == KeyEvent.VK_UP) {
                evt.consume();
                controller.previousTributVR();
            } else if (keyCode == KeyEvent.VK_ESCAPE) {
                this.setVisible(false);
            } else if (keyCode == KeyEvent.VK_F2) {
//                btnIncluir.doClick();
            } else if (keyCode == KeyEvent.VK_F3) {
                btnIncluirtodas.doClick();
            } else {
                pesquisar();
            }
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
            Util.exibirMensagemErro(ex, "");
        }
    }//GEN-LAST:event_classBuscaNcm1KeyRelesed

    private void classBuscaNcm1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_classBuscaNcm1KeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }

        if (classBuscaNcm1.getText().length() >= 4) {
            evt.consume();
        }
    }//GEN-LAST:event_classBuscaNcm1KeyTyped

    private void classBuscaNcm2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_classBuscaNcm2KeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c) && c != '.' && c != ',') {
            evt.consume();
        }

        if (classBuscaNcm2.getText().length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_classBuscaNcm2KeyTyped

    private void classBuscaNcm2KeyRelesed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_classBuscaNcm2KeyRelesed
        pesquisar();
    }//GEN-LAST:event_classBuscaNcm2KeyRelesed

    private void classBuscaNcm3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_classBuscaNcm3KeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c) && c != '.' && c != ',') {
            evt.consume();
        }

        if (classBuscaNcm3.getText().length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_classBuscaNcm3KeyTyped

    private void classBuscaNcm3KeyRelesed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_classBuscaNcm3KeyRelesed
        pesquisar();
    }//GEN-LAST:event_classBuscaNcm3KeyRelesed

    private void CknExibirTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CknExibirTodosActionPerformed
        controller.setExibirTodos(CknExibirTodos.isSelected());

        try {
            controller.atualizarMapa();
        } catch (Exception e) {
            Exceptions.printStackTrace(e);
        }
    }//GEN-LAST:event_CknExibirTodosActionPerformed

    private void pesquisar() {
        try {
            String ncm1 = classBuscaNcm1.getText().trim();
            String ncm2 = classBuscaNcm2.getText().trim();
            String ncm3 = classBuscaNcm3.getText().trim();

            if (ncm1.isEmpty() && ncm2.isEmpty() && ncm3.isEmpty()) {
                return;
            }

            controller.buscar(ncm1, ncm2, ncm3);

        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
            Util.exibirMensagemErro(ex, "Erro ao fazer a pesquisa de Classificações no VR");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JCheckBox CknExibirTodos;
    javax.swing.JButton btnAtualizar;
    javax.swing.JButton btnIncluir;
    javax.swing.JButton btnIncluirtodas;
    javax.swing.JTextField classBuscaNcm1;
    javax.swing.JTextField classBuscaNcm2;
    javax.swing.JTextField classBuscaNcm3;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    vrframework.bean.tableEx.VRTableEx tblMapa;
    vrframework.bean.tableEx.VRTableEx tblVR;
    javax.swing.JTextField txtAgrupador;
    javax.swing.JTextField txtSistema;
    // End of variables declaration//GEN-END:variables

    void refresh() throws Exception {
        List<VRColumnTable> vColunaProduto = new ArrayList();
        vColunaProduto.add(new VRColumnTable("Código Ant.", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("Código Class. Ant.", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("Ncm1 Ant", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("Ncm2 Ant", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("Ncm3 Ant.", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable(" - - ", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("Cód. VR", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("Cód. Class VR", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("Ncm1 VR", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("Ncm2 VR", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("Ncm3 VR", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("ID Ncm VR", true, SwingConstants.CENTER, false, null));
        tblMapa.configurarColuna(vColunaProduto, this, "Mapa", "mapaClassificaçõesNcm");

        Object[][] dados = new Object[controller.getMapa().size()][tblMapa.getvColuna().size()];
        int i = 0;
        for (MapaReformaTributariaClassificacaoNcmVO classificacaoNcm : controller.getMapa()) {

            dados[i][0] = classificacaoNcm.getOrigId();
            dados[i][1] = classificacaoNcm.getOrigIdClassificacao();
            dados[i][2] = classificacaoNcm.getOrigNcm1();
            dados[i][3] = classificacaoNcm.getOrigNcm2();
            dados[i][4] = classificacaoNcm.getOrigNcm3();
            dados[i][5] = " >>>> ";
            if (classificacaoNcm.getClassificacaoNcm() == null) {
                dados[i][6] = "";
                dados[i][7] = "";
                dados[i][8] = "";
                dados[i][9] = "";
                dados[i][10] = "";
                dados[i][11] = "";
            } else {

                dados[i][6] = classificacaoNcm.getClassificacaoNcm().getId();
                dados[i][7] = classificacaoNcm.getClassificacaoNcm().getIdClassificacao();
                dados[i][8] = classificacaoNcm.getClassificacaoNcm().getNcm1();
                dados[i][9] = classificacaoNcm.getClassificacaoNcm().getNcm2();
                dados[i][10] = classificacaoNcm.getClassificacaoNcm().getNcm3();
                dados[i][11] = classificacaoNcm.getClassificacaoNcm().getIdNcm();
            }
            i++;
        }

        tblMapa.setModel(dados);
        tblMapa.setRowHeight(30);
        tblMapa.atualizarTamanhoColuna();
        if (tblMapa.getRowCount() > 0) {
            tblMapa.setLinhaSelecionada(0);
        }
    }

    void refreshBusca() throws Exception {
        List<VRColumnTable> vColunaProduto = new ArrayList();
        vColunaProduto.add(new VRColumnTable("ID NCM - VR", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("NCM 1 - VR", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("NCM 2 - VR", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("NCM 3 - VR", true, SwingConstants.CENTER, false, null));
        vColunaProduto.add(new VRColumnTable("Descricao", true, SwingConstants.LEFT, false, null));
        tblVR.configurarColuna(vColunaProduto, this, "NCM", "ncms");

        Object[][] dados = new Object[controller.getNcmsVR().size()][tblVR.getvColuna().size()];
        int i = 0;
        for (NcmVO ncm : controller.getNcmsVR()) {

            dados[i][0] = ncm.getId();
            dados[i][1] = ncm.getNcm1();
            dados[i][2] = ncm.getNcm2();
            dados[i][3] = ncm.getNcm3();
            dados[i][4] = ncm.getDescricao();

            i++;
        }

        tblVR.setModel(dados);
        tblVR.setRowHeight(30);
        tblVR.atualizarTamanhoColuna();
        if (tblVR.getRowCount() > 0) {
            tblVR.setLinhaSelecionada(0);
        }
    }
}
