/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vrimplantacao2.gui.component.mapatiporecebiveis;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.SwingConstants;
import org.openide.util.Exceptions;
import vrframework.bean.table.VRColumnTable;
import vrframework.classe.Util;
import vrimplantacao2.vo.cadastro.financeiro.TipoRecebivelVO;
import vrimplantacao2.vo.enums.Icms;

/**
 *
 * @author Leandro
 */
public class MapaTipoRecebiveisView extends javax.swing.JPanel {
    
    private MapaTipoRecebiveisController controller = new MapaTipoRecebiveisController(this);    
    private FinanceiroProvider provider;

    public FinanceiroProvider getProvider() {
        return provider;
    }
    
    public void setProvider(FinanceiroProvider provider) throws Exception {
        this.provider = provider;
        this.controller.setProvider(provider);
        this.refresh();
    }
    
    /**
     * Creates new form MapaRecebiveisCaixaView
     */
    public MapaTipoRecebiveisView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBusca = new javax.swing.JTextField();
        btnIncluir = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tblVR = new vrframework.bean.tableEx.VRTableEx();
        tblMapa = new vrframework.bean.tableEx.VRTableEx();
        jLabel1 = new javax.swing.JLabel();
        txtSistema = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAgrupador = new javax.swing.JTextField();

        txtBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaKeyRelesed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnIncluir, "Incluir (F1)");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnAtualizar, "Altualizar Listagem");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarOnClick(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, "Buscar");

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, "Sistema");

        txtSistema.setEditable(false);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, "Agrupador");

        txtAgrupador.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tblVR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBusca, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtualizar))
                    .addComponent(tblMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtSistema))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtAgrupador, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 267, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizar)
                    .addComponent(btnIncluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblVR, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblMapa, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAgrupador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscaKeyRelesed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaKeyRelesed
        try {
            int keyCode = evt.getKeyCode();
            evt.consume();
            if (keyCode == KeyEvent.VK_ENTER) {
                txtBusca.selectAll();
                controller.gravar();
            } else if (keyCode == KeyEvent.VK_DOWN) {
                controller.nextVR();
            } else if (keyCode == KeyEvent.VK_UP) {
                controller.previousVR();
            } else if (keyCode == KeyEvent.VK_F1) {
                controller.incluir();
            } else if (keyCode == KeyEvent.VK_ESCAPE) {
                //Fecha a tela
            } else {
                controller.buscar(txtBusca.getText());
            }
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
            Util.exibirMensagemErro(ex, "");
        }
    }//GEN-LAST:event_txtBuscaKeyRelesed

    private void btnAtualizarOnClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarOnClick
        try {
            controller.atualizarMapa();
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
            Util.exibirMensagemErro(ex, "");
        }
    }//GEN-LAST:event_btnAtualizarOnClick

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        try {
            controller.incluir();
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
            Util.exibirMensagemErro(ex, "");
        }
    }//GEN-LAST:event_btnIncluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAtualizar;
    public javax.swing.JButton btnIncluir;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public vrframework.bean.tableEx.VRTableEx tblMapa;
    public vrframework.bean.tableEx.VRTableEx tblVR;
    public javax.swing.JTextField txtAgrupador;
    public javax.swing.JTextField txtBusca;
    public javax.swing.JTextField txtSistema;
    // End of variables declaration//GEN-END:variables

    void refresh() throws Exception {
        txtSistema.setText(provider.getSistema());
        txtAgrupador.setText(provider.getLojaOrigem());
        
        List<VRColumnTable> colunas = new ArrayList<>();
        colunas.add(new VRColumnTable("Código", true, SwingConstants.LEFT, false, null));
        colunas.add(new VRColumnTable("Descrição", true, SwingConstants.LEFT, false, null));
        colunas.add(new VRColumnTable("Código VR", true, SwingConstants.LEFT, false, null));
        colunas.add(new VRColumnTable("Descrição VR", true, SwingConstants.LEFT, false, null));
        colunas.add(new VRColumnTable("Porc.(%)", true, SwingConstants.LEFT, false, null));
        tblMapa.configurarColuna(colunas, this, "mapatributacao", "");
        
        Object[][] dados = new Object[controller.getMapa().size()][tblMapa.getvColuna().size()];
        for (int i = 0; i < controller.getMapa().size(); i++) {
            MapaTipoRecebivelVO row = controller.getMapa().get(i);
            
            dados[i][0] = row.getId();
            dados[i][1] = row.getDescricao();
            if (row.getCodigoatual()== null) {
                dados[i][2] = "";
                dados[i][3] = "";
                dados[i][4] = "";
            } else {
                dados[i][2] = String.valueOf(row.getCodigoatual().getId());
                dados[i][3] = row.getCodigoatual().getDescricao();
                dados[i][4] = String.format("%.2f", row.getCodigoatual().getPercentual()) + "%";
            }            
        }
        tblMapa.setModel(dados);
        tblMapa.setRowHeight(30);
        tblMapa.atualizarTamanhoColuna();
        if (tblMapa.getRowCount() > 0) {
            tblMapa.setLinhaSelecionada(0);
        }
    }
    
    void refreshBusca() throws Exception {
        List<VRColumnTable> vColunaProduto = new ArrayList();      
        vColunaProduto.add(new VRColumnTable("Cód. VR", true, SwingConstants.LEFT, false, null));
        vColunaProduto.add(new VRColumnTable("Descrição", true, SwingConstants.LEFT, false, null));
        vColunaProduto.add(new VRColumnTable("Perc.(%)", true, SwingConstants.LEFT, false, null));
        tblVR.configurarColuna(vColunaProduto, this, "Trib", "tributos");
        
        Object[][] dados = new Object[controller.getTiposRecebiveis().size()][tblVR.getvColuna().size()];
        int i = 0;
        for (TipoRecebivelVO recebivel: controller.getTiposRecebiveis()) {
            
            dados[i][0] = recebivel.getId();
            dados[i][1] = recebivel.getDescricao();
            dados[i][2] = String.format("%.2f", recebivel.getPercentual());
            
            i++;
        }            

        tblVR.setModel(dados);
        tblVR.setRowHeight(30);
        tblVR.atualizarTamanhoColuna();
        if (tblVR.getRowCount() > 0) {
            tblVR.setLinhaSelecionada(0);
        }
    }

}
