/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vrimplantacao2.vo.enums;

/**
 *
 * @author Leandro
 */
public enum TipoAlinea {
    A0_VALIDO (0,"CHEQUE VALIDO"),
    A11_SEM_FUNDO_1 (11,"CHEQUE SEM FUNDOS 1  APRESENTACAO"),
    A12_SEM_FUNDO_2 (12,"CHEQUE SEM FUNDOS 2  APRESENTACAO"),
    A13_CONTA_ENCERRADA (13,"CONTA ENCERRADA"),
    A14_PRATICA_ESPURIA (14,"PRATICA ESPURIA"),
    A15_DEVOLVIDO_ALINEA_LOJA (15,"DEVOLVIDO ALINEA DA PROPRIA LOJA"),
    A20_CHEQUE_CANCELADO_POR_CORRENTISTA (20,"CHEQUE CANCELADO POR SOLICITACAO DO CORRENTISTA"),
    A21_CONTRA_ORDEM (21,"CONTRA-ORDEM"),
    A22_DIVERGENCIA_ASSINATURA (22,"DIVERGENCIA OU INSUFICIENCIA DE ASSINATURA"),
    A23_EMITENTE_FEDERAL_EM_DESACORDO (23,"EMITENTE ENT/ ORG ADM PUBL. FED EM DESACORDO"),
    A24_BLOQUEIO_JUCICIAL (24,"BLOQUEIO JUDICIAL OU DETERMINACAO BACEM"),
    A25_CANCELAMENTO_TALONARIO (25,"CANCELAMENTO TALONARIO PELO BANCO SACADO"),
    A26_INOPERANCIA_TRANSPORTE (26,"INOPERANCIA TEMPORARIA DE TRANSPORTE"),
    A27_FEIRADO_MUNICIAL (27,"FERIADO MUNICIPAL NAO PREVISTO"),
    A28_CONTRA_ORDEM_POR_FURTO (28,"CONTRA ORDEM OU OPOSICAO POR FURTO OU ROUBO"),
    A29_CHEQUE_BLOQUEADO (29,"CHEQ BLOQ FALTA CONFIRM REC TALON PELO CORRENT"),
    A30_ROUBO_MALOTE (30,"FURTO OU ROUBO DE MALOTE"),
    A31_ERRO_NORMAL (31,"ERRO NORMAL"),
    A32_ENDOSSO_IRREGURAR (32,"AUSENCIA/IRREGULARIDADE NA APLIC.CARIMBO ENDOSO"),
    A33_ENDOSSO_DIVERGENTE (33,"DIVERGENCIA ENDOSSO"),
    A34_CN_APRESENTADO (34,"CN APRESENT P/BANCO QUE NAO O IND.CRUZAMENTO"),
    A35_FRAUDADO (35,"CHEQUE FRAUDADO"),
    A36_MAIS_DE_UM_ENDOSSO (36,"CHEQUE COM MAIS DE UM ENDOSSO"),
    A37_REGISTRO_INCONSISTENTE (37,"REGISTRO INCONSISTENTE - COMPENSACAO ELETRONICA"),
    A40_MOEDA_INVALIDA (40,"MOEDA IVALIDA (SOMENTE CHEQUES)"),
    A41_APRESENTADO_BCO_NAO_SACADO (41,"CHEQUE APRESENTADO A BANCO QUE NAO O SACADO"),
    A42_NAO_COMPENSAVEL_NA_SECAO (42,"CHEQUE NAO COMPENSAVEL NA SECAO"),
    A43_CH_DEV_ANTERIORMENTE (43,"CH.DEV.ANTERIORMENTE PO MOT : 21/22/23/24/31/34"),
    A44_PRESCRITO (44,"CHEQUE PRESCRITO"),
    A45_CH_ENTID_OBRIG_MOV (45,"CH.ENTID.OBRIG.MOV.REC.FIN.MEDIANTE ORDEM BACEM"),
    A46_DV_CR_NAO_RECEBIDO (46,"DEVOLUCAO DE CR - CHEQUE NAO RECEBIDO"),
    A47_DV_CR_INCONSISTENTE (47,"DEVOLUCAO DE CR - DADOS INCONSISTENTES"),
    A48_MAIOR_Q_100_NAO_NOMINAL (48,"CH. VALOR SUPERIOR A R$100,00 NAO NOMINATIVO"),
    A49_REMESSA_NULA (49,"REMESSA NULA"),
    A50_SEM_EXPRESSAO_TRANSF (50,"AUSENCIA EXPRESSAO TRANSF INT EM REAIS - NAT OP"),
    A55_DEVOLVIDO_EM_TRANSITO (55,"CH DEVOLVIDO EM TRANSITO - 2  REAPRESENTACAO"),
    A61_NAO_COMPENSAVEL (61,"DOCUMENTO NAO COMPENSAVEL"),
    A64_ARQUIVO_PROCESSADO_PARCIALMENTE (64,"ARQUIVO LOGICO PROCESSADO PARCIALMENTE"),
    A66_CLIENTE_PREF_REJEITADO (66,"CADASTRO CLIENTE PREFERENCIAL REJEITADO"),
    A70_SUSTACAO_REVOG_PROV (70,"Sustação ou Revogação Provisória"),
    A77_CH_DEVOLVIDO_E_REAPRESENTACAO (77,"CH DEVOLVIDO E REAPRESENTADO - 1  DEVOLUCAO");

    /**
     * Verifica a existencia da alinea e retorna o valor correto.
     * @param alinea Código da alinea.
     * @return Se a alinea existir, retorna um {@link TipoAlinea} correspondente,
     * senão retorna {@link TipoAlinea#A0_VALIDO}.
     */
    public static TipoAlinea getAlinea(int alinea) {
        for (TipoAlinea alin: values()) {
            if (alin.getId() == alinea) {
                return alin;
            }
        }
        return A0_VALIDO;
    }

    private int id;
    private String descricao;

    private TipoAlinea(int id, String descricao) {
        this.id = id;
        this.descricao = descricao;
    }

    public int getId() {
        return id;
    }

    public String getDescricao() {
        return descricao;
    }
    
}
