package vrimplantacao2_5.dao.atualizador;

import java.sql.ResultSet;
import java.sql.Statement;
import vrimplantacao2_5.vo.enums.EBancoDados;
import vrimplantacao2_5.vo.enums.ESistema;
import vrframework.classe.Conexao;

/**
 *
 * @author Desenvolvimento
 */
public class AtualizadorDAO {

    public boolean verificarBancoDados(EBancoDados eBancoDados) throws Exception {
        try (Statement stm = Conexao.createStatement()) {
            try (ResultSet rs = stm.executeQuery(
                    "select nome \n"
                    + "from implantacao2_5.bancodados \n"
                    + "where nome = '" + eBancoDados.getNome() + "'"
            )) {
                return rs.next();
            }
        }
    }

    public boolean verificarSistema(ESistema eSistema) throws Exception {
        try (Statement stm = Conexao.createStatement()) {
            try (ResultSet rs = stm.executeQuery(
                    "select nome \n"
                    + "from implantacao2_5.sistema \n"
                    + "where nome = '" + eSistema.getNome() + "'"
            )) {
                return rs.next();
            }
        }
    }

    public void criarSchema() throws Exception {
        try (Statement stm = Conexao.createStatement()) {
            stm.execute("CREATE SCHEMA IF NOT EXISTS implantacao2_5");
        }
    }

    public void criarTabelas() throws Exception {
        try (Statement stm = Conexao.createStatement()) {
            stm.execute(
                    "CREATE TABLE IF NOT EXISTS implantacao2_5.bancodados(\n"
                    + "	id integer PRIMARY KEY NOT NULL,\n"
                    + "	nome VARCHAR(60) NOT NULL\n"
                    + ");"
                    + "\n"
                    + "CREATE TABLE IF NOT EXISTS implantacao2_5.sistema(\n"
                    + "	id integer PRIMARY KEY NOT NULL,\n"
                    + "	nome VARCHAR(60) NOT NULL\n"
                    + ");\n"
                    + "\n"
                    + "CREATE TABLE IF NOT EXISTS implantacao2_5.sistemabancodados(\n"
                    + "	id serial PRIMARY KEY NOT NULL,\n"
                    + "	id_sistema INTEGER NOT NULL,\n"
                    + "	id_bancodados INTEGER NOT NULL,\n"
                    + "	nomeschema VARCHAR(60),\n"
                    + "	usuario VARCHAR(30),\n"
                    + "	senha VARCHAR(30),\n"
                    + "	CONSTRAINT fk_id_sistema FOREIGN KEY (id_sistema)\n"
                    + "		REFERENCES implantacao2_5.sistema (id),\n"
                    + "	CONSTRAINT fk_id_bancodados FOREIGN KEY (id_bancodados)\n"
                    + "		REFERENCES implantacao2_5.bancodados (id),\n"
                    + "	CONSTRAINT un_sistema_bancodados \n"
                    + "		UNIQUE (id_sistema, id_bancodados)\n"
                    + ");"
                    + "\n"
                    + "CREATE TABLE IF NOT EXISTS implantacao2_5.conexao(\n"
                    + "	id serial PRIMARY KEY NOT NULL,\n"
                    + "	host VARCHAR(20) NOT NULL,\n"
                    + " nomeschema VARCHAR(255) NOT NULL,"
                    + "	porta INTEGER NOT NULL,\n"
                    + "	usuario VARCHAR(30) NOT NULL,\n"
                    + "	senha VARCHAR(30) NOT NULL,\n"
                    + "	descricao VARCHAR(100),\n"
                    + " id_sistema integer NOT NULL,\n"
                    + " id_bancodados integer NOT NULL,\n"
                    + " complemento varchar(10) NULL,\n"
                    + " CONSTRAINT un_conexao_sistema UNIQUE (id_sistema, complemento),\n"        
                    + " CONSTRAINT fk_id_bancodados FOREIGN KEY (id_bancodados)\n"
                    + "         REFERENCES implantacao2_5.bancodados (id) MATCH SIMPLE\n"
                    + "      ON UPDATE NO ACTION ON DELETE NO ACTION,\n"
                    + " CONSTRAINT fk_id_sistema FOREIGN KEY (id_sistema)\n"
                    + "         REFERENCES implantacao2_5.sistema (id) MATCH SIMPLE\n"
                    + "      ON UPDATE NO ACTION ON DELETE NO ACTION,\n"
                    + " CONSTRAINT un_sistema_bancodados_host_nomeschema_conexao UNIQUE (id_sistema, id_bancodados, host, nomeschema)\n"
                    + ");"
                    + "\n"
                    + "CREATE TABLE IF NOT EXISTS implantacao2_5.conexaoloja(\n"
                    + "	id serial PRIMARY KEY NOT NULL,\n"
                    + "	id_conexao INTEGER NOT NULL,\n"
                    + "	id_lojaorigem VARCHAR NOT NULL,\n"
                    + "	id_lojadestino INTEGER NOT NULL,\n"
                    + "	datacadastro TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),\n"
                    + "	id_situacaomigracao INTEGER NOT NULL,\n"
                    + "	lojamatriz BOOLEAN,\n"
                    + "	CONSTRAINT fk_if_conexao FOREIGN KEY (id_conexao)\n"
                    + "		REFERENCES implantacao2_5.conexao(id)\n"
                    + ");"
                    + "\n"
                    + "ALTER TABLE implantacao2_5.conexaoloja \n"
                    + "ADD CONSTRAINT fk_id_lojadestino \n"
                    + "FOREIGN KEY (id_lojadestino) REFERENCES loja(id);"
            );
        }
    }

    public void salvarBancoDados(EBancoDados eBancoDados) throws Exception {
        try (Statement stm = Conexao.createStatement()) {
            stm.execute(
                    "INSERT INTO implantacao2_5.bancodados (id, nome) \n"
                    + "VALUES (\n"
                    + eBancoDados.getId() + ", \n"
                    + "'" + eBancoDados.getNome() + "'\n"
                    + ");");
        }
    }

    public void salvarSistema(ESistema eSistema) throws Exception {
        try (Statement stm = Conexao.createStatement()) {
            stm.execute("INSERT INTO implantacao2_5.sistema (id, nome) \n"
                    + "VALUES (\n"
                    + eSistema.getId() + ", \n"
                    + "'" + eSistema.getNome() + "'\n"
                    + ")");
        }
    }

    public void salvarSistemaBancoDados() throws Exception {
        try (Statement stm = Conexao.createStatement()) {
            
            stm.execute(
                    "DELETE FROM implantacao2_5.sistemabancodados; \n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = '" + ESistema.ACCESYS + "'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = '" + EBancoDados.SQLSERVER + "'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = '"+ESistema.ACOM+"'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = '"+EBancoDados.SQLSERVER+"'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = '"+ESistema.ALPHASYS+"'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = '"+EBancoDados.FIREBIRD+"'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = '"+ESistema.APOLLO+"'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = '"+EBancoDados.ORACLE+"'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = '"+ESistema.ARIUS+"'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = '"+EBancoDados.ORACLE+"'), 'PROREG', 'automa', null);\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = '"+ESistema.ARTSYSTEM+"'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = '"+EBancoDados.SQLSERVER+"'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = '"+ESistema.ASEFE+"'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = '"+EBancoDados.SQLSERVER+"'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'ASOFT'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'ATENAS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'ATHOS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'POSTGRESQL'), 'athos', 'j2mhw82dyu1kn5g4', null);   	 \n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'ATMA'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'AUTOADM'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'AUTOCOM'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'AUTOSYSTEM'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'POSTGRESQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'AVANCE'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'), 'root', 'infor', null);\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'AVISTARE'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'), 'sa', '@vs2008', 'Avistare');	 	\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'BASE'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'ACCESS'));	 	\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'BRAJANGESTORES'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'POSTGRESQL'));	 	\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'CADASTRAFACIL'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));	 	\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'CEFAS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'ORACLE'));	 	\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'CEREBRO'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));	 	\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'CERVANTES'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'POSTGRESQL'));	 	\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'CFSOFTSIAECF'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));	 	\n"
                    + "	 \n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'CGA'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'), 'SYSDBA', 'masterkey', null);\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'CISS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'DB2'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'CLICK'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'CONTROLWARE'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'POSTGRESQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'CONTROLX'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'CPGESTOR'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'ORACLE'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'CPLUS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'CRONOS20'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'POSTGRESQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'CUPERMAX'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'ORACLE'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'DATASYNC'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER')); \n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'DELFI'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD')); \n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'DESTRO'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD')); \n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'DEVMASTER'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'POSTGRESQL'), 'devmaster', 'devmaster', null); \n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'DIRECTOR'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'), 'sa', '#1qwer0987', null);   	   \n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'DJSYSTEM'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'DBF'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'DLINK'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'DSOFT'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'DTCOM'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'DBF'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'EASYSAC'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'EMPORIO'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'EPTUS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'ESSYSTEM'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'DBF'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'ETICA'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'EXODUS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'FABTECH'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'FACILITE'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'FENIX'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'FHONLINE'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'FLASH'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'FLATAN'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'POSTGRESQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'FORT'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'FUTURA'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'G10'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'POSTGRESQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'G3'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'GCOM'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'GDI'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'GDOOR'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'GESTORPDV'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'GETWAY'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'), 'gws', 'gws', 'GWOLAP');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'GIGATRON'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'GONDOLA'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'ORACLE'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'GR7'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'GTECH'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'GUIASISTEMAS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'GZSISTEMAS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'), 'root', 'mestre', null);\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'HERCULESINTCASH'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'HIPCOM'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'), 'root', 'hpc00', null);\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'HIPER'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'HRTECH'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'ICOMMERCE'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'INFOBRASIL'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'INFOMAC'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'ORACLE'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'INOVA'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'POSTGRESQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'INTELLICASH'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'), 'SYSDBA', 'k', null);\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'INTELLICON'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'INTERAGE'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'), 'SYSDBA', 'masterkey');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'INTERDATA'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'INVENTER'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'IQSISTEMAS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'ISERVER'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'), 'root', '750051', 'db_iserver');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'JACSYS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'DBF'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'JM2ONLINE'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'JMASTER'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'JRF'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'POSTGRESQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'KAIROS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'KCMS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'LINCE'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'LINEAR'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'), 'adminlinear', '@2013linear', 'sglinx');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'LINNER'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'ORACLE'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'LITECI'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'LOGICBOX'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'LOGTEC'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'POSTGRESQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'LOGUS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'INFORMIX'), 'informix', 'loooge', null);\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'LYNCIS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'POSTGRESQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'MARKET'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'POSTGRESQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'MASTER'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'MERCALITE'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'MILENIO'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'MOBILITY'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'), 'SYSDBA', 'masterkey');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'MOBNEPDV'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'MRS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'POSTGRESQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'MSIINFOR'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'DBF'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'NATISISTEMAS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'NCA'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'POSTGRESQL'), 'postgres', 'post');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'OPEN'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'ORION'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'DBF'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'ORIONTECH'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, senha)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'ORYON'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'ACCESS'), 'paralelo');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'PHIXA'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'PLENOKW'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'PLENUS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'POLIGON'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'), 'sa', 'Pol!gon5oft', 'PADARIA');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'POMARES'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'PROTON'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'ORACLE'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'PWGESTOR'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'PWS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'RCNET'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'RENSOFTWARE'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'REPLEIS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'RESULTMAIS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'POSTGRESQL'), 'postgres', 'rmpostgres', 'rmbancodados');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'RKSOFTWARE'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'), 'SYSDBA', 'Office25');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'RMS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'ORACLE'), 'rms', 'rmsprd');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'RMSAUTOMAHELP'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'POSTGRESQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'ROOTAC'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'DBF'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'RPINFO'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'POSTGRESQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SAAC'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SABTECH'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SAEF'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SATECFE'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SAV'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SCEF'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SDINFORMATICA'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SGMASTER'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SHI'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'), 'SYSDBA', 'masterkey');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SIAC'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'ORACLE'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SIACRIARE'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'), 'root', 'Hs8Tw13kPx7uDPs');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SIFAT'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SIGMA'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SIIT'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'), 'root', 'JesusCristo');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SIRCOM'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'), 'SYSDBA', 'masterkey');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SISMOURA'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SNSISTEMA'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SOFTCOM'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SOFTTECH'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'POSTGRESQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SOLIDUS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SOLIDUS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'ORACLE'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SOLUTIONSUPERA'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'), 'SYSDBA', 'online');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SOPHYX'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SRI'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'STI'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'STSITEMAS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SUPER'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SUPERLOJA10'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SUPERSERVER'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SUPERUS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'ORACLE'), 'xe', 'smart');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SYNCTEC'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SYSAUT'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'), 'SYSDBA', 'masterkey');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SYSERP'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SYSMO'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SYSMO'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'POSTGRESQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SYSPDV'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));	 	 \n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'SYSPDV'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'), 'SYSDBA', 'masterkey');	 	 \n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'TECNOSOFT'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'TELECON'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'), 'sa', 'a2m8x7h5', 'GESTAO');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'TGA'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'TITECNOLOGIA'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'TOPSYSTEM'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'TPAROOTAC'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'TSTI'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'MYSQL'), 'tsti', '1234', 'tsl');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'UNIPLUS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'POSTGRESQL'), 'postgres', 'postgres');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'UPFORTI'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'VCASH'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'DBF'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'VIASOFT'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'ORACLE'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'VIGGO'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'POSTGRESQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'VISUALCOMERCIO'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'VISUALMIX'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha, nomeschema)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'VRMASTER'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'POSTGRESQL'), 'postgres', 'VrPost@Server', 'vr');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'ZOOMBOX'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'POSTGRESQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'ZPF'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'));\n"
                    + "	 \n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, senha)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'W2A'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'ACCESS'), 'banco820318');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'WEBER'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'), 'SYSDBA', 'masterkey');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'WEBSAQ'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'POSTGRESQL'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'WINNEXUS'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'SQLSERVER'));\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados, usuario, senha)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'WISASOFT'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'FIREBIRD'), 'SYSDBA', 'masterkey');\n"
                    + "\n"
                    + "INSERT INTO implantacao2_5.sistemabancodados (id_sistema, id_bancodados)\n"
                    + "VALUES ((SELECT id FROM implantacao2_5.sistema\n"
                    + "	 WHERE nome = 'WMSI'),\n"
                    + "	 (SELECT id FROM implantacao2_5.bancodados\n"
                    + "	 WHERE nome = 'ORACLE'));"
            );
        }
    }
}
