/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vrimplantacao2_5.nutricional.GUI;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Desenvolvimento
 */
public class InstrucoesNutricionalArquivo extends javax.swing.JFrame {

    /**
     * Creates new form IntrucoesNutricionalArquivo
     */
    public InstrucoesNutricionalArquivo() {
        initComponents(); 
        setLocationRelativeTo(null);
        passo1.setForeground(Color.ORANGE);
        passo1.setOpaque(true);
        conteudo1.setContentType("text/html");
        conteudo1.setEditable(false);
        conteudo1.setBackground(Color.WHITE);
        conteudo1.setOpaque(true);
        conteudo1.setText("<html>"
                + "<body>"
                + "<p align = \"justify\"><font size = 5>"
                + "         Certifique-se de ter carregado, verificado e, caso necessário, editado os arquivos.<br>"
                + "         Para isso bastava carregar e salvar.<br>"
                + "         Se pulou essas etapas, volte e salve os arquivos."
                + "</p></font>"
                + "</body"
                + "</html");
        conteudo1.setCaretPosition(0);
        passo2.setForeground(Color.ORANGE);
        passo2.setOpaque(true);
        conteudo2.setContentType("text/html");
        conteudo2.setEditable(false);
        conteudo2.setBackground(Color.WHITE);
        conteudo2.setOpaque(true);
        conteudo2.setText("<html>"
                + "<body>"
                + "<p align = \"left\"><font size = 5>"
                + "         Escolha o script simplificado e clique em migrar.<br>"
                + "         Caso esse script não te atenda você pode edita-lo.<br>"
                + "         Para ajudar na edição você pode usar os scripts prontos, tanto o simplificado quando o completo,"
                + "         porém precisa se atentar em dar os alias (apelidos)"
                + "         corretamente para os campos ou a importação não funcionará.<br>"
                + "         Use o script completo para conhecer os alias.<br>"
                + "         Uma vez editado todo o script, basta clicar em migrar.<br>"
                + "         Ao clicar em migrar o sistema sempre vai carregar o script que está area de texto.<br>"
                + "</p></font>"
                + "</body"
                + "</html");
        conteudo2.setCaretPosition(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        img = new javax.swing.JLabel();
        passo1 = new javax.swing.JLabel();
        passo2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        scrollConteudo1 = new javax.swing.JScrollPane();
        conteudo1 = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        conteudo2 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(InstrucoesNutricionalArquivo.class, "InstrucoesNutricionalArquivo.title_1")); // NOI18N

        img.setBackground(new java.awt.Color(204, 0, 0));
        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vrimplantacao2_5/nutricional/utils/vrsoftware.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(img, org.openide.util.NbBundle.getMessage(InstrucoesNutricionalArquivo.class, "InstrucoesNutricionalArquivo.img.text")); // NOI18N

        passo1.setBackground(new java.awt.Color(0, 0, 0));
        passo1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(passo1, org.openide.util.NbBundle.getMessage(InstrucoesNutricionalArquivo.class, "InstrucoesNutricionalArquivo.passo1.text")); // NOI18N

        passo2.setBackground(new java.awt.Color(0, 0, 0));
        passo2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(passo2, org.openide.util.NbBundle.getMessage(InstrucoesNutricionalArquivo.class, "InstrucoesNutricionalArquivo.passo2.text")); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        scrollConteudo1.setBorder(null);

        conteudo1.setEditable(false);
        conteudo1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        scrollConteudo1.setViewportView(conteudo1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollConteudo1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollConteudo1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane4.setBorder(null);

        conteudo2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jScrollPane4.setViewportView(conteudo2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                    .addComponent(passo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img)
                .addGap(18, 18, 18)
                .addComponent(passo1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passo2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstrucoesNutricionalArquivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstrucoesNutricionalArquivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstrucoesNutricionalArquivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstrucoesNutricionalArquivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstrucoesNutricionalArquivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane conteudo1;
    private javax.swing.JTextPane conteudo2;
    private javax.swing.JLabel img;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel passo1;
    private javax.swing.JLabel passo2;
    private javax.swing.JScrollPane scrollConteudo1;
    // End of variables declaration//GEN-END:variables
}
