package vrimplantacao2_5.gui.sistema.checks;

/**
 *
 * @author Lucas
 */
public class ChecksOptionsHipcomPanelGUI extends javax.swing.JTabbedPane {

    public ChecksOptionsHipcomPanelGUI() {
        super();
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgPautaFiscal = new javax.swing.ButtonGroup();
        vRCheckBox3 = new vrframework.bean.checkBox.VRCheckBox();
        scrollParametros = new javax.swing.JScrollPane();
        tabParametros = new vrframework.bean.panel.VRPanel();
        vRCheckBox1 = new vr.view.components.checkbox.VRCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(vRCheckBox3, "vRCheckBox3");

        scrollParametros.setBorder(null);
        scrollParametros.setPreferredSize(new java.awt.Dimension(593, 219));

        tabParametros.setPreferredSize(new java.awt.Dimension(300, 219));
        tabParametros.setLayout(null);

        org.openide.awt.Mnemonics.setLocalizedText(vRCheckBox1, "Importar Icms Entrada (Cad)");
        tabParametros.add(vRCheckBox1);
        vRCheckBox1.setBounds(10, 10, 181, 25);

        scrollParametros.setViewportView(tabParametros);

        addTab("Parâmetros Hipcom", scrollParametros);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup btgPautaFiscal;
    public javax.swing.JScrollPane scrollParametros;
    public vrframework.bean.panel.VRPanel tabParametros;
    public vr.view.components.checkbox.VRCheckBox vRCheckBox1;
    public vrframework.bean.checkBox.VRCheckBox vRCheckBox3;
    // End of variables declaration//GEN-END:variables
    
}
