package vrimplantacao2_5.gui.sistema.checks;

/**
 *
 * @author Lucas
 */
public class ChecksOptionsVRPanelGUI extends javax.swing.JTabbedPane {

    public ChecksOptionsVRPanelGUI() {
        super();
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgPautaFiscal = new javax.swing.ButtonGroup();
        vRCheckBox3 = new vrframework.bean.checkBox.VRCheckBox();
        scrollParametros = new javax.swing.JScrollPane();
        tabParametros = new vrframework.bean.panel.VRPanel();
        chkEANAtacado = new vrframework.bean.checkBox.VRCheckBox();
        chkSomenteAtivo = new vrframework.bean.checkBox.VRCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(vRCheckBox3, "vRCheckBox3");

        scrollParametros.setBorder(null);
        scrollParametros.setPreferredSize(new java.awt.Dimension(593, 219));

        tabParametros.setPreferredSize(new java.awt.Dimension(300, 219));
        tabParametros.setLayout(null);

        org.openide.awt.Mnemonics.setLocalizedText(chkEANAtacado, "Importar EAN Atacado");
        tabParametros.add(chkEANAtacado);
        chkEANAtacado.setBounds(10, 40, 133, 23);

        org.openide.awt.Mnemonics.setLocalizedText(chkSomenteAtivo, "Somente Produto Ativo");
        tabParametros.add(chkSomenteAtivo);
        chkSomenteAtivo.setBounds(10, 10, 137, 23);

        scrollParametros.setViewportView(tabParametros);

        addTab("Parâmetros VR", scrollParametros);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup btgPautaFiscal;
    public vrframework.bean.checkBox.VRCheckBox chkEANAtacado;
    public vrframework.bean.checkBox.VRCheckBox chkSomenteAtivo;
    public javax.swing.JScrollPane scrollParametros;
    public vrframework.bean.panel.VRPanel tabParametros;
    public vrframework.bean.checkBox.VRCheckBox vRCheckBox3;
    // End of variables declaration//GEN-END:variables
    
}
