package vrimplantacao2.gui.component.mapatributacao.incluiraliquota;

import java.awt.Dimension;
import org.openide.util.Exceptions;
import vrframework.bean.dialog.VRDialog;
import vrimplantacao.dao.cadastro.AliquotaDAO;
import vrimplantacao.utils.Utils;
import vrimplantacao2.utils.MathUtils;

/**
 *
 * @author Leandro
 */
public class IncluirAliquotaGUI extends VRDialog {

    public static int exibir(int cst, double aliquota, double reduzido, String descricao) throws Exception {
        IncluirAliquotaGUI gui = new IncluirAliquotaGUI();
        
        gui.setModal(true);
        gui.setTitle("Incluir alíquota");
        gui.centralizarForm();
        
        gui.setMinimumSize(new Dimension(390, 126));
        
        gui.txtCst.setInt(cst);
        gui.txtAliquota.setDouble(aliquota);
        gui.txtReduzido.setDouble(reduzido);
        gui.txtDescricao.setText(Utils.acertarTexto(descricao, 15));
        
        gui.setVisible(true);        
        
        return gui.getResult();
    }

    private int result = -1;

    public int getResult() {
        return result;
    }
    
    /**
     * Creates new form IncluirAliquotaGUI
     * @throws java.lang.Exception
     */
    public IncluirAliquotaGUI() throws Exception {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDescricao = new vrframework.bean.textField.VRTextField();
        txtCst = new vrframework.bean.textField.VRTextField();
        txtAliquota = new vrframework.bean.textField.VRTextField();
        txtReduzido = new vrframework.bean.textField.VRTextField();
        txtAliqFinal = new vrframework.bean.textField.VRTextField();
        chkGerarPDV = new vrframework.bean.checkBox.VRCheckBox();
        btnIncluir = new vrframework.bean.button.VRButton();
        vRLabel1 = new vrframework.bean.label.VRLabel();
        vRLabel2 = new vrframework.bean.label.VRLabel();
        vRLabel3 = new vrframework.bean.label.VRLabel();
        vRLabel4 = new vrframework.bean.label.VRLabel();
        vRLabel5 = new vrframework.bean.label.VRLabel();

        setMinimumSize(new java.awt.Dimension(460, 168));

        txtDescricao.setColumns(15);
        txtDescricao.setText(org.openide.util.NbBundle.getMessage(IncluirAliquotaGUI.class, "IncluirAliquotaGUI.txtDescricao.text")); // NOI18N

        txtCst.setText(org.openide.util.NbBundle.getMessage(IncluirAliquotaGUI.class, "IncluirAliquotaGUI.txtCst.text")); // NOI18N
        txtCst.setMascara(org.openide.util.NbBundle.getMessage(IncluirAliquotaGUI.class, "IncluirAliquotaGUI.txtCst.mascara")); // NOI18N

        txtAliquota.setText(org.openide.util.NbBundle.getMessage(IncluirAliquotaGUI.class, "IncluirAliquotaGUI.txtAliquota.text")); // NOI18N
        txtAliquota.setMascara(org.openide.util.NbBundle.getMessage(IncluirAliquotaGUI.class, "IncluirAliquotaGUI.txtAliquota.mascara")); // NOI18N
        txtAliquota.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAliquotaFocusLost(evt);
            }
        });

        txtReduzido.setText(org.openide.util.NbBundle.getMessage(IncluirAliquotaGUI.class, "IncluirAliquotaGUI.txtReduzido.text")); // NOI18N
        txtReduzido.setMascara(org.openide.util.NbBundle.getMessage(IncluirAliquotaGUI.class, "IncluirAliquotaGUI.txtReduzido.mascara")); // NOI18N
        txtReduzido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAliquotaFocusLost(evt);
            }
        });

        txtAliqFinal.setText(org.openide.util.NbBundle.getMessage(IncluirAliquotaGUI.class, "IncluirAliquotaGUI.txtAliqFinal.text")); // NOI18N
        txtAliqFinal.setEnabled(false);
        txtAliqFinal.setMascara(org.openide.util.NbBundle.getMessage(IncluirAliquotaGUI.class, "IncluirAliquotaGUI.txtAliqFinal.mascara")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(chkGerarPDV, org.openide.util.NbBundle.getMessage(IncluirAliquotaGUI.class, "IncluirAliquotaGUI.chkGerarPDV.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnIncluir, org.openide.util.NbBundle.getMessage(IncluirAliquotaGUI.class, "IncluirAliquotaGUI.btnIncluir.text")); // NOI18N
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(vRLabel1, org.openide.util.NbBundle.getMessage(IncluirAliquotaGUI.class, "IncluirAliquotaGUI.vRLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(vRLabel2, org.openide.util.NbBundle.getMessage(IncluirAliquotaGUI.class, "IncluirAliquotaGUI.vRLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(vRLabel3, org.openide.util.NbBundle.getMessage(IncluirAliquotaGUI.class, "IncluirAliquotaGUI.vRLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(vRLabel4, org.openide.util.NbBundle.getMessage(IncluirAliquotaGUI.class, "IncluirAliquotaGUI.vRLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(vRLabel5, org.openide.util.NbBundle.getMessage(IncluirAliquotaGUI.class, "IncluirAliquotaGUI.vRLabel5.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCst, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vRLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAliquota, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vRLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtReduzido, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vRLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vRLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAliqFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkGerarPDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vRLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAliquota, txtCst, txtReduzido});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vRLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vRLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vRLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vRLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vRLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAliquota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReduzido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAliqFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkGerarPDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAliquotaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAliquotaFocusLost
        calcularAliquotaFinal();
    }//GEN-LAST:event_txtAliquotaFocusLost

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        try {
            result = new AliquotaDAO().aliquota(txtCst.getInt(), txtAliquota.getDouble(), txtReduzido.getDouble(), txtDescricao.getText(), chkGerarPDV.isSelected());
            this.setVisible(false);
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
            throw new RuntimeException(ex);
        }
    }//GEN-LAST:event_btnIncluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vrframework.bean.button.VRButton btnIncluir;
    private vrframework.bean.checkBox.VRCheckBox chkGerarPDV;
    private vrframework.bean.textField.VRTextField txtAliqFinal;
    private vrframework.bean.textField.VRTextField txtAliquota;
    private vrframework.bean.textField.VRTextField txtCst;
    private vrframework.bean.textField.VRTextField txtDescricao;
    private vrframework.bean.textField.VRTextField txtReduzido;
    private vrframework.bean.label.VRLabel vRLabel1;
    private vrframework.bean.label.VRLabel vRLabel2;
    private vrframework.bean.label.VRLabel vRLabel3;
    private vrframework.bean.label.VRLabel vRLabel4;
    private vrframework.bean.label.VRLabel vRLabel5;
    // End of variables declaration//GEN-END:variables

    private void calcularAliquotaFinal() {
        try {
            double aliquotaFinal = MathUtils.round(txtAliquota.getDouble() * ((100 - txtReduzido.getDouble()) / 100), 2);
            txtAliqFinal.setDouble(aliquotaFinal);
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
            throw new RuntimeException(ex);
        }
    }
}
